#! /usr/local/bin/tcsh -f

latex 04-15
bibtex 04-15
latex 04-15
latex 04-15
dvips 04-15.dvi -o 04-15.ps 
distill -resolution 2400 -colordownsample off -graydownsample off -monodownsample off -cmykimagestorgb off 04-15.ps
