#! /usr/local/bin/tcsh -f

latex 04-15
dvips 04-15.dvi -o 04-15.ps 
#distill -embedallfonts on -resolution 2400 -colordownsample off -graydownsample off -monodownsample off -cmykimagestorgb off 04-15.ps

ps2pdf 04-15.ps




