#! /usr/local/bin/tcsh -f

latex budget
bibtex budget
latex budget
latex budget
dvips budget.dvi -o budget.ps 
distill -resolution 2400 -colordownsample off -graydownsample off -monodownsample off -cmykimagestorgb off budget.ps
