#! /usr/local/bin/tcsh -f

latex 04-17
bibtex 04-17
latex 04-17
latex 04-17
dvips 04-17.dvi -o 04-17.ps 
distill -resolution 2400 -colordownsample off -graydownsample off -monodownsample off -cmykimagestorgb off 04-17.ps
