#! /usr/local/bin/tcsh -f

latex 04-14
bibtex 04-14
latex 04-14
latex 04-14
dvips 04-14.dvi -o 04-14.ps 
distill -resolution 2400 -colordownsample off -graydownsample off -monodownsample off -cmykimagestorgb off 04-14.ps
