#! /usr/local/bin/tcsh -f

chmod 664 04-22.tex
latex 04-22
dvips 04-22.dvi -o 04-22.ps 
distill -resolution 2400 -colordownsample off -graydownsample off -monodownsample off -cmykimagestorgb off 04-22.ps
