#! /usr/local/bin/tcsh -f

latex 05-10
bibtex 05-10
latex 05-10
latex 05-10
dvips 05-10.dvi -o 05-10.ps 
distill -resolution 2400 -colordownsample off -graydownsample off -monodownsample off -cmykimagestorgb off 05-10.ps


