#! /usr/local/bin/tcsh -f

latex 04-21
bibtex 04-21
latex 04-21
latex 04-21
dvips 04-21.dvi -o 04-21.ps 
distill -resolution 2400 -colordownsample off -graydownsample off -monodownsample off -cmykimagestorgb off 04-21.ps
