#! /usr/local/bin/tcsh -f

latex 06-04
bibtex 06-04
latex 06-04
latex 06-04
dvips 06-04.dvi -o 06-04.ps 
#distill -resolution 2400 -colordownsample off -graydownsample off -monodownsample off -cmykimagestorgb off 06-04.ps
