#! /usr/local/bin/tcsh -f

latex bio
bibtex bio
latex bio
latex bio
dvips bio.dvi -o bio.ps 
distill -resolution 2400 -colordownsample off -graydownsample off -monodownsample off -cmykimagestorgb off bio.ps
