#! /usr/local/bin/tcsh -f

latex nasa
bibtex nasa
latex nasa
latex nasa
dvips nasa.dvi -o nasa.ps 
distill -resolution 2400 -colordownsample off -graydownsample off -monodownsample off -cmykimagestorgb off nasa.ps
