#! /usr/local/bin/tcsh -f

# Generate initial reference files (*.toc, *.aux, *.log, *.bbl, etc.)
latex 03-05
# Run bibtex to generate bibliography from reference files
bibtex 03-05
# Now run latex twice more to include biblio stuff and resolve references and page numbers.
latex 03-05
latex 03-05
# Convert dvi file to postscript
dvips 03-05.dvi -o 03-05.ps 
# Convert postscript to pdf.
distill -resolution 2400 -colordownsample off 03-05.ps
