<html>
<head>
<title>LEAP Data File</title>
</head>
<body>
<table border>
<tr>
<td>DRL Plain 1.0.0
<tr>
<th>CreateDate<th>DocID<th>FixTime<th>Location<th>Occurrences<th>DefectType<th>Severity<th>Description<th>Valid<th>UserCreated<th>UserFound<th>Injected<th>Removed<th>Checklist
<tr>
<td type=CreateDate>1998/07/17
<td type=DocID>
<td type=FixTime>
<td type=Location>
<td type=Occurrences>
<td type=DefectType>
<td type=Severity>
<td type=Description>
<td type=Valid>
<td type=UserCreated>
<td type=UserFound>
<td type=Injected>
<td type=Removed>
<td type=Checklist>
<tr>
<td type=CreateDate>1998/07/17
<td type=DocID>ch4.pdf
<td type=FixTime>
<td type=Location>27-19
<td type=Occurrences>1
<td type=DefectType>30: Content
<td type=Severity>
<td type=Description>fixed:   It would be very helpful to indicate the number of times
each correction rule was applied (since that was a 
complaint raised about our experimental design).  It
might also be useful (both here and elsewhere) to comment
upon the issue of "introducing" error through correction that 
makes our conclusions invalid. 
<td type=Valid>
<td type=UserCreated>
<td type=UserFound>
<td type=Injected>
<td type=Removed>
<td type=Checklist>
<tr>
<td type=CreateDate>1998/07/17
<td type=DocID>ch4.pdf
<td type=FixTime>
<td type=Location>26-17
<td type=Occurrences>1
<td type=DefectType>10:Syntax
<td type=Severity>
<td type=Description>fixed:   backwards facing quotation marks
<td type=Valid>
<td type=UserCreated>
<td type=UserFound>
<td type=Injected>
<td type=Removed>
<td type=Checklist>
<tr>
<td type=CreateDate>1998/07/17
<td type=DocID>ch4.pdf
<td type=FixTime>
<td type=Location>21
<td type=Occurrences>1
<td type=DefectType>30: Content
<td type=Severity>
<td type=Description>There is an issue here with respect to experimental
design: what is our experimental design?  There
probably needs to be an additional section in this
chapter that characterizes the "experiment" as 
qualitative and uncontrolled.  Probably see Kitchenham or
someone like that for terminology and so forth.
<td type=Valid>
<td type=UserCreated>
<td type=UserFound>
<td type=Injected>
<td type=Removed>
<td type=Checklist>
<tr>
<td type=CreateDate>1998/07/17
<td type=DocID>ch4.pdf
<td type=FixTime>
<td type=Location>21-6
<td type=Occurrences>1
<td type=DefectType>20:Organization
<td type=Severity>
<td type=Description>fixed:   Add a sentence summarizing what this chapter
will include content-wise.
<td type=Valid>
<td type=UserCreated>
<td type=UserFound>
<td type=Injected>
<td type=Removed>
<td type=Checklist>
<tr>
<td type=CreateDate>1998/07/17
<td type=DocID>ch4.pdf
<td type=FixTime>
<td type=Location>21-9
<td type=Occurrences>1
<td type=DefectType>10:Syntax
<td type=Severity>
<td type=Description>fixed:   passive voice
<td type=Valid>
<td type=UserCreated>
<td type=UserFound>
<td type=Injected>
<td type=Removed>
<td type=Checklist>
<tr>
<td type=CreateDate>1998/07/17
<td type=DocID>ch4.pdf
<td type=FixTime>
<td type=Location>21-7
<td type=Occurrences>1
<td type=DefectType>30: Content
<td type=Severity>
<td type=Description>fixed:    "In order to produce data of the highest possible quality"
probably overstates things.  Perhaps, "In order to address
data quality problems discovered in previous semesters", 
<td type=Valid>
<td type=UserCreated>
<td type=UserFound>
<td type=Injected>
<td type=Removed>
<td type=Checklist>
</table>

</body>
</html>
