#! /usr/local/bin/tcsh -f

latex 06-03
bibtex 06-03
latex 06-03
latex 06-03
dvips 06-03.dvi -o 06-03.ps 
distill -resolution 2400 -colordownsample off -graydownsample off -monodownsample off -cmykimagestorgb off 06-03.ps


