#! /usr/local/bin/tcsh -f

chmod 664 06-10.tex
latex 06-10
dvips 06-10.dvi -o 06-10.ps 
distill -resolution 2400 -colordownsample off -graydownsample off -monodownsample off -cmykimagestorgb off 06-10.ps
