#! /usr/local/bin/tcsh -f

# Generate initial reference files (*.toc, *.aux, *.log, *.bbl, etc.)
latex 03-10
# Run bibtex to generate bibliography from reference files
bibtex 03-10
# Now run latex twice more to include biblio stuff and resolve references and page numbers.
latex 03-10
latex 03-10
# Convert dvi file to postscript
dvips 03-10.dvi -o 03-10.ps 
# Convert postscript to pdf.
distill -resolution 2400 -colordownsample off 03-10.ps
