#! /usr/local/bin/tcsh -f

latex nsf
bibtex nsf
latex nsf
latex nsf
dvips nsf.dvi -o nsf.ps 
distill -resolution 2400 -colordownsample off -graydownsample off -monodownsample off -cmykimagestorgb off nsf.ps
