#! /usr/local/bin/tcsh -f

latex summary
bibtex summary
latex summary
latex summary
dvips summary.dvi -o summary.ps 
distill -resolution 2400 -colordownsample off -graydownsample off -monodownsample off -cmykimagestorgb off summary.ps
