#! /usr/local/bin/tcsh -f

# Generate initial reference files (*.toc, *.aux, *.log, *.bbl, etc.)
latex 03-04   
# Run bibtex to generate bibliography from reference files
bibtex 03-04
# Now run latex twice more to include biblio stuff and resolve references and page numbers.
latex 03-04
latex 03-04
# Convert dvi file to postscript
dvips 03-04.dvi -o 03-04.ps 
# Convert postscript to pdf.
distill -resolution 2400 -colordownsample off 03-04.ps

