#! /usr/local/bin/tcsh -f

chmod 664 06-06.tex
latex 06-06
dvips 06-06.dvi -o 06-06.ps 
distill -resolution 2400 -colordownsample off -graydownsample off -monodownsample off -cmykimagestorgb off 06-06.ps
