<html>
<head>
<title>LEAP Data File</title>
</head>
<body>
<table border>
<tr>
<td>DRL Plain 1.0.0
<tr>
<th>CreateDate<th>DocID<th>FixTime<th>Location<th>Occurrences<th>DefectType<th>Severity<th>Description<th>Valid<th>UserCreated<th>UserFound<th>Injected<th>Removed<th>Checklist
<tr>
<td type=CreateDate>16:05 07/30/1998
<td type=DocID>proposal.pdf
<td type=FixTime>1
<td type=Location>1.1Problem
<td type=Occurrences>1
<td type=DefectType>30: Content
<td type=Severity>Low,3
<td type=Description>Is a sophisticated WWW interface an archive.  This sounds strange to me.
<td type=Valid>
<td type=UserCreated>
<td type=UserFound>
<td type=Injected>
<td type=Removed>
<td type=Checklist>
<tr>
<td type=CreateDate>16:06 07/30/1998
<td type=DocID>proposal.pdf
<td type=FixTime>1
<td type=Location>2.2 Goals
<td type=Occurrences>1
<td type=DefectType>30: Content
<td type=Severity>Low,3
<td type=Description>The goal of adoption is never addressed in this section.  The two goals mentioned are directly related to adoption.
<td type=Valid>
<td type=UserCreated>
<td type=UserFound>
<td type=Injected>
<td type=Removed>
<td type=Checklist>
<tr>
<td type=CreateDate>16:11 07/30/1998
<td type=DocID>proposal.pdf
<td type=FixTime>1
<td type=Location>2.3 Target mailing list
<td type=Occurrences>1
<td type=DefectType>30: Content
<td type=Severity>Low,3
<td type=Description>Are the criteria for selecting "ascend-users" generic for all MCS mailing lists.  If so then this should appear somewhere in the document.
<td type=Valid>
<td type=UserCreated>
<td type=UserFound>
<td type=Injected>
<td type=Removed>
<td type=Checklist>
<tr>
<td type=CreateDate>16:12 07/30/1998
<td type=DocID>proposal.pdf
<td type=FixTime>1
<td type=Location>2.3.1 Classes of user
<td type=Occurrences>1
<td type=DefectType>30: Content
<td type=Severity>Low,3
<td type=Description>Who categorized the users?
<td type=Valid>
<td type=UserCreated>
<td type=UserFound>
<td type=Injected>
<td type=Removed>
<td type=Checklist>
<tr>
<td type=CreateDate>16:14 07/30/1998
<td type=DocID>proposal.pdf
<td type=FixTime>1
<td type=Location>2.4, 2.5, 2.6
<td type=Occurrences>1
<td type=DefectType>30: Content
<td type=Severity>Medium,2
<td type=Description>Transitions are missing.  
<td type=Valid>
<td type=UserCreated>
<td type=UserFound>
<td type=Injected>
<td type=Removed>
<td type=Checklist>
<tr>
<td type=CreateDate>16:15 07/30/1998
<td type=DocID>proposal.pdf
<td type=FixTime>1
<td type=Location>Chpt 3
<td type=Occurrences>1
<td type=DefectType>30: Content
<td type=Severity>Low,3
<td type=Description>Change the name of this chapter.  You are not doing an experiment.  Maybe Evaluation.
<td type=Valid>
<td type=UserCreated>
<td type=UserFound>
<td type=Injected>
<td type=Removed>
<td type=Checklist>
<tr>
<td type=CreateDate>16:16 07/30/1998
<td type=DocID>proposal.pdf
<td type=FixTime>1
<td type=Location>3.3.1
<td type=Occurrences>1
<td type=DefectType>30: Content
<td type=Severity>Medium,2
<td type=Description>Are there any concrete numbers or standards you can define to measure adoption.  Like if 30% of the active users use MCS then it has been adopted.  Right now it sounds like a lot of hand waving.
<td type=Valid>
<td type=UserCreated>
<td type=UserFound>
<td type=Injected>
<td type=Removed>
<td type=Checklist>
<tr>
<td type=CreateDate>16:18 07/30/1998
<td type=DocID>proposal.pdf
<td type=FixTime>1
<td type=Location>3.3
<td type=Occurrences>1
<td type=DefectType>30: Content
<td type=Severity>Medium,2
<td type=Description>How is the different types of data you are collecting going to be evaluated to determine if MCS is better than regular archives.  An example of the data and how you are going to combine it together to determine the adoption of MCS would be very helpful.
<td type=Valid>
<td type=UserCreated>
<td type=UserFound>
<td type=Injected>
<td type=Removed>
<td type=Checklist>
<tr>
<td type=CreateDate>16:20 07/30/1998
<td type=DocID>proposal.pdf
<td type=FixTime>1
<td type=Location>Chpt 5
<td type=Occurrences>1
<td type=DefectType>30: Content
<td type=Severity>Low,3
<td type=Description>Should there be a mention of HI-TIME?  I sure hope not!
<td type=Valid>
<td type=UserCreated>
<td type=UserFound>
<td type=Injected>
<td type=Removed>
<td type=Checklist>
<tr>
<td type=CreateDate>16:21 07/30/1998
<td type=DocID>proposal.pdf
<td type=FixTime>1
<td type=Location>App B
<td type=Occurrences>1
<td type=DefectType>30: Content
<td type=Severity>Medium,2
<td type=Description>Are you going to do the interviews?  If so then there is no problem with the interview questions.  You will have to evaluate the users to determine their level.
<td type=Valid>
<td type=UserCreated>
<td type=UserFound>
<td type=Injected>
<td type=Removed>
<td type=Checklist>
<tr>
<td type=CreateDate>16:23 07/30/1998
<td type=DocID>proposal.pdf
<td type=FixTime>1
<td type=Location>App B,C
<td type=Occurrences>1
<td type=DefectType>30: Content
<td type=Severity>Medium,2
<td type=Description>"Three times a week" is too exact, what if they use it only twice a week?  Perhaps it should be "About three times a week".
<td type=Valid>
<td type=UserCreated>
<td type=UserFound>
<td type=Injected>
<td type=Removed>
<td type=Checklist>
<tr>
<td type=CreateDate>16:24 07/30/1998
<td type=DocID>proposal.pdf
<td type=FixTime>1
<td type=Location>App C
<td type=Occurrences>1
<td type=DefectType>30: Content
<td type=Severity>Medium,2
<td type=Description>Define the different user levels so the users can select the one that matches them.
<td type=Valid>
<td type=UserCreated>
<td type=UserFound>
<td type=Injected>
<td type=Removed>
<td type=Checklist>
</table>

</body>
</html>
