<html>
<head>
<title>LEAP Data File</title>
</head>
<body>
<table border>
<tr>
<td>DRL Plain 1.0.0
<tr>
<th>CreateDate<th>DocID<th>FixTime<th>Location<th>Occurrences<th>DefectType<th>Severity<th>Description<th>Valid<th>UserCreated<th>UserFound<th>Injected<th>Removed<th>Checklist
<tr>
<td type=CreateDate>16:25 08/03/1998
<td type=DocID>proposal.pdf
<td type=FixTime>1
<td type=Location>
<td type=Occurrences>1
<td type=DefectType>40:Format
<td type=Severity>Low,3
<td type=Description>Use Times font. Computer Modern is lame and does
not show up well in pdf viewers.


<td type=Valid>
<td type=UserCreated>
<td type=UserFound>
<td type=Injected>
<td type=Removed>
<td type=Checklist>
<tr>
<td type=CreateDate>16:26 08/03/1998
<td type=DocID>RunLeap
<td type=FixTime>1
<td type=Location>honu
<td type=Occurrences>1
<td type=DefectType>30:Bug
<td type=Severity>Medium,2
<td type=Description>DocID field is not defaulting.  Weird: it wasn't defaulting for
the first few rows, then all of  a sudden it began defaulting. Huh?

<td type=Valid>
<td type=UserCreated>
<td type=UserFound>
<td type=Injected>
<td type=Removed>
<td type=Checklist>
<tr>
<td type=CreateDate>16:27 08/03/1998
<td type=DocID>proposal.pdf
<td type=FixTime>1
<td type=Location>3-15
<td type=Occurrences>1
<td type=DefectType>30: Content
<td type=Severity>Low,3
<td type=Description>Addendum: Another failing of FAQs is that they cannot answer a
frequently asked question whose answer frequently changes, such as
"What is the most stable recent release of this system." This
is because FAQs are generally used to answer important
questions whose answers don't change alot, since that would
impose overhead on the maintainer. (Support for this scenario
is a key advantage of MCS.

<td type=Valid>
<td type=UserCreated>
<td type=UserFound>
<td type=Injected>
<td type=Removed>
<td type=Checklist>
<tr>
<td type=CreateDate>16:32 08/03/1998
<td type=DocID>proposal.pdf
<td type=FixTime>1
<td type=Location>3-21
<td type=Occurrences>1
<td type=DefectType>30: Content
<td type=Severity>Medium,2
<td type=Description>MCS does *not* extract useful information "in the same way"
that knowledge in newspapers get condensed into books; 
you probably need to be more careful with that choice of
wording.

<td type=Valid>
<td type=UserCreated>
<td type=UserFound>
<td type=Injected>
<td type=Removed>
<td type=Checklist>
<tr>
<td type=CreateDate>
<td type=DocID>proposal.pdf
<td type=FixTime>
<td type=Location>3-21
<td type=Occurrences>1
<td type=DefectType>30: Content
<td type=Severity>High,1
<td type=Description>In this paragraph, it would be better if you added a sentence
or two to explain why condensation is going to overcome
the problems inherent with FAQs and searchable archives.
<td type=Valid>
<td type=UserCreated>
<td type=UserFound>
<td type=Injected>
<td type=Removed>
<td type=Checklist>
<tr>
<td type=CreateDate>16:39 08/03/1998
<td type=DocID>proposal.pdf
<td type=FixTime>1
<td type=Location>3-1
<td type=Occurrences>1
<td type=DefectType>30: Content
<td type=Severity>High,1
<td type=Description>Somewhere in this first chapter, you need to supply a specific question
that a user might realistically have of a mailing list archive that
is not well answered by either the archive format or the 
FAQ format, but which is well-supported by your system.
You could have an additional section called "An example"
if you want to split it out, or you could thread the example 
through the chapter.  That way you tie down this abstract
discussion to something concrete that the reader can get
a handle on.  A screen dump of a made-up web interface would be excellent.

<td type=Valid>
<td type=UserCreated>
<td type=UserFound>
<td type=Injected>
<td type=Removed>
<td type=Checklist>
<tr>
<td type=CreateDate>16:42 08/03/1998
<td type=DocID>proposal.pdf
<td type=FixTime>1
<td type=Location>4-25
<td type=Occurrences>1
<td type=DefectType>30: Content
<td type=Severity>High,1
<td type=Description>I think you need to elaborate this thesis statement a bit and 
operationalize the terms "adopted", "useful", "prefer" and "current existing".

<td type=Valid>
<td type=UserCreated>
<td type=UserFound>
<td type=Injected>
<td type=Removed>
<td type=Checklist>
<tr>
<td type=CreateDate>16:44 08/03/1998
<td type=DocID>proposal.pdf
<td type=FixTime>1
<td type=Location>6-3
<td type=Occurrences>1
<td type=DefectType>30: Content
<td type=Severity>Medium,2
<td type=Description>Question: at one time, we spoke of having a link to the original message
within the condensed one. Is that still being planned? If so, it should be
mentionned.
<td type=Valid>
<td type=UserCreated>
<td type=UserFound>
<td type=Injected>
<td type=Removed>
<td type=Checklist>
<tr>
<td type=CreateDate>16:50 08/03/1998
<td type=DocID>proposal.pdf
<td type=FixTime>1
<td type=Location>7-4
<td type=Occurrences>1
<td type=DefectType>30: Content
<td type=Severity>Medium,2
<td type=Description>You need to try to indicate whether or not the ascend list characteristics are
a one-of-a-kind anachronism (thus indicating that MCS won't have any
generality), or whether (at least in your opinion, perhaps substantiated by a list of 
a half dozen or so other lists) that the ascend-users list is representative
of a reasonably-sized class of mailing lists.
<td type=Valid>
<td type=UserCreated>
<td type=UserFound>
<td type=Injected>
<td type=Removed>
<td type=Checklist>
<tr>
<td type=CreateDate>08:56 08/04/1998
<td type=DocID>proposal.pdf
<td type=FixTime>1
<td type=Location>10-18
<td type=Occurrences>1
<td type=DefectType>20:Organization
<td type=Severity>Medium,2
<td type=Description>It would be nice to include a mockup interface to "Symptom-based problem
solution lookup", as well as to the other operational scenarios.
<td type=Valid>
<td type=UserCreated>
<td type=UserFound>
<td type=Injected>
<td type=Removed>
<td type=Checklist>
<tr>
<td type=CreateDate>09:00 08/04/1998
<td type=DocID>proposal.pdf
<td type=FixTime>1
<td type=Location>8-19
<td type=Occurrences>1
<td type=DefectType>20:Organization
<td type=Severity>Medium,2
<td type=Description>What you are calling "operational scenarios" really arent. They are more like
loosely described functional requirements. To see examples of real
operational scenarios, check out the PSPBase software requirements
specification (csdl tr 96-19).  It is amazing how much missing detail is
exposed when you try to write a true operational scenario for a system.
<td type=Valid>
<td type=UserCreated>
<td type=UserFound>
<td type=Injected>
<td type=Removed>
<td type=Checklist>
<tr>
<td type=CreateDate>
<td type=DocID>proposal.pdf
<td type=FixTime>
<td type=Location>14-37
<td type=Occurrences>1
<td type=DefectType>30: Content
<td type=Severity>Low,3
<td type=Description>It might also be interesting to log the amount of time it takes an editor
to perform his duties, or log the amount of time it takes a user to bring
up the system and satisfy a request. Even ballpark measures of time
overhead might be interesting in assessing adoption potential.

Also, if there was some way to get a handle on the percentage or frequency of 
failure to get the answer to a question, that would be good.
<td type=Valid>
<td type=UserCreated>
<td type=UserFound>
<td type=Injected>
<td type=Removed>
<td type=Checklist>
<tr>
<td type=CreateDate>
<td type=DocID>proposal.pdf
<td type=FixTime>
<td type=Location>
<td type=Occurrences>
<td type=DefectType>
<td type=Severity>
<td type=Description>
<td type=Valid>
<td type=UserCreated>
<td type=UserFound>
<td type=Injected>
<td type=Removed>
<td type=Checklist>
</table>

</body>
</html>
