<html>
<head>
<title>LEAP Data File</title>
</head>
<body>
<table border>
<tr>
<td>DRL Plain 1.0.0
<tr>
<th>CreateDate<th>DocID<th>FixTime<th>Location<th>Occurrences<th>DefectType<th>Severity<th>Description<th>Valid<th>UserCreated<th>UserFound<th>Injected<th>Removed<th>Checklist
<tr>
<td type=CreateDate>11:11 07/28/1998
<td type=DocID>RunLeap
<td type=FixTime>1
<td type=Location>Honu
<td type=Occurrences>1
<td type=DefectType>10:Usability
<td type=Severity>
<td type=Description>"Clear DataSource" button label is meaningless to non-developers
<td type=Valid>
<td type=UserCreated>
<td type=UserFound>
<td type=Injected>
<td type=Removed>
<td type=Checklist>
<tr>
<td type=CreateDate>11:14 07/28/1998
<td type=DocID>RunLeap
<td type=FixTime>1
<td type=Location>Honu
<td type=Occurrences>1
<td type=DefectType>10:Usability
<td type=Severity>
<td type=Description>The description field gets completely filled with a horizontal scrollbar when halfway through typing so you can't even see what your're typing.  I suggest the workaround of making each table row at least two lines deep to start, then when this is fixed we canmake the table rows smaller.Funny: this only seemed to happen on the FIRST row!
<td type=Valid>
<td type=UserCreated>
<td type=UserFound>
<td type=Injected>
<td type=Removed>
<td type=Checklist>
<tr>
<td type=CreateDate>11:21 07/28/1998
<td type=DocID>RunLeap
<td type=FixTime>
<td type=Location>Honu
<td type=Occurrences>1
<td type=DefectType>10:Usability
<td type=Severity>
<td type=Description>The current textfield editor seems to ignore newlines when reformattingthe contents of the description field, so I can't create multipleparagraphs separated by a couple of newlines.  Not good.
<td type=Valid>
<td type=UserCreated>
<td type=UserFound>
<td type=Injected>
<td type=Removed>
<td type=Checklist>
<tr>
<td type=CreateDate>11:22 07/28/1998
<td type=DocID>RunLeap
<td type=FixTime>1
<td type=Location>Honu
<td type=Occurrences>1
<td type=DefectType>10:Usability
<td type=Severity>
<td type=Description>Row index should be one-based, not zero-based.
<td type=Valid>
<td type=UserCreated>
<td type=UserFound>
<td type=Injected>
<td type=Removed>
<td type=Checklist>
<tr>
<td type=CreateDate>11:24 07/28/1998
<td type=DocID>RunLeap
<td type=FixTime>1
<td type=Location>Honu
<td type=Occurrences>1
<td type=DefectType>10:Usability
<td type=Severity>
<td type=Description>Could we default the Location and DefectType fields?  Couldthe fields to default be a user-controlled thing by having a dialog box (similar to the show/hide columns?) That would be awesome. 
<td type=Valid>
<td type=UserCreated>
<td type=UserFound>
<td type=Injected>
<td type=Removed>
<td type=Checklist>
<tr>
<td type=CreateDate>11:25 07/28/1998
<td type=DocID>ch7.pdf
<td type=FixTime>1
<td type=Location>62-9
<td type=Occurrences>1
<td type=DefectType>10:Syntax
<td type=Severity>
<td type=Description>Fixed:  "As a summary of"..  becomes "To summarize.." to remove the "it will be useful at this point" cruft.
<td type=Valid>
<td type=UserCreated>
<td type=UserFound>
<td type=Injected>
<td type=Removed>
<td type=Checklist>
<tr>
<td type=CreateDate>11:49 07/28/1998
<td type=DocID>ch7.pdf
<td type=FixTime>
<td type=Location>63-3
<td type=Occurrences>1
<td type=DefectType>10:Syntax
<td type=Severity>
<td type=Description>Fixed:  "There are two types of detectable errors:"
<td type=Valid>
<td type=UserCreated>
<td type=UserFound>
<td type=Injected>
<td type=Removed>
<td type=Checklist>
<tr>
<td type=CreateDate>11:50 07/28/1998
<td type=DocID>ch7.pdf
<td type=FixTime>1
<td type=Location>63-3
<td type=Occurrences>1
<td type=DefectType>20:Organization
<td type=Severity>
<td type=Description>Tried (looked bad): Perhaps make a table for detectable and hidden types.
<td type=Valid>
<td type=UserCreated>
<td type=UserFound>
<td type=Injected>
<td type=Removed>
<td type=Checklist>
<tr>
<td type=CreateDate>11:50 07/28/1998
<td type=DocID>ch7.pdf
<td type=FixTime>1
<td type=Location>63-19
<td type=Occurrences>1
<td type=DefectType>10:Syntax
<td type=Severity>
<td type=Description>Fixed:  "Given reliable primary data"
<td type=Valid>
<td type=UserCreated>
<td type=UserFound>
<td type=Injected>
<td type=Removed>
<td type=Checklist>
<tr>
<td type=CreateDate>11:51 07/28/1998
<td type=DocID>ch7.pdf
<td type=FixTime>1
<td type=Location>65-17
<td type=Occurrences>1
<td type=DefectType>30: Content
<td type=Severity>
<td type=Description>Fixed:  The problem for the instructor is worse than you describe it, becauseI *DO* evaluate people to some extent based upon the number ofdefects recorded.  If a student is recording say, 0 or 1 defects perproject, then I definitely question this result, even though I knowthat it is probably creating measurement dysfunction. But the alternative is to let them slide into recording no defects at all.(I also assume that my comments lead to them making up data.)
<td type=Valid>
<td type=UserCreated>
<td type=UserFound>
<td type=Injected>
<td type=Removed>
<td type=Checklist>
<tr>
<td type=CreateDate>11:53 07/28/1998
<td type=DocID>ch7.pdf
<td type=FixTime>1
<td type=Location>
<td type=Occurrences>1
<td type=DefectType>30: Content
<td type=Severity>
<td type=Description>I love footnotes 3, 4, 5, 6, 7.  Somehow we need to keep them in :-)
<td type=Valid>
<td type=UserCreated>
<td type=UserFound>
<td type=Injected>
<td type=Removed>
<td type=Checklist>
<tr>
<td type=CreateDate>11:54 07/28/1998
<td type=DocID>ch7.pdf
<td type=FixTime>1
<td type=Location>69-18
<td type=Occurrences>1
<td type=DefectType>30: Content
<td type=Severity>
<td type=Description>Fixed:  Do you want to include my estimate of the number of forms fromthe SEI rebuttal email?  I think it would be useful to includeto give people a concrete idea of how many thousands of valuesare being manipulated.
<td type=Valid>
<td type=UserCreated>
<td type=UserFound>
<td type=Injected>
<td type=Removed>
<td type=Checklist>
<tr>
<td type=CreateDate>11:55 07/28/1998
<td type=DocID>ch7.pdf
<td type=FixTime>
<td type=Location>75-3
<td type=Occurrences>1
<td type=DefectType>30: Content
<td type=Severity>
<td type=Description>Fixed:  I hate to say this, but if you have time, it would be really niceto redo the form with the shaded grey boxes and show a beforeand after screen dump in the text.
<td type=Valid>
<td type=UserCreated>
<td type=UserFound>
<td type=Injected>
<td type=Removed>
<td type=Checklist>
<tr>
<td type=CreateDate>11:56 07/28/1998
<td type=DocID>ch7.pdf
<td type=FixTime>
<td type=Location>77-1
<td type=Occurrences>1
<td type=DefectType>20:Organization
<td type=Severity>
<td type=Description>Fixed:  OK to move the diary entries to the tool chapter. I think they're reallyquite interesting.
<td type=Valid>
<td type=UserCreated>
<td type=UserFound>
<td type=Injected>
<td type=Removed>
<td type=Checklist>
<tr>
<td type=CreateDate>11:59 07/28/1998
<td type=DocID>
<td type=FixTime>
<td type=Location>
<td type=Occurrences>
<td type=DefectType>
<td type=Severity>
<td type=Description>
<td type=Valid>
<td type=UserCreated>
<td type=UserFound>
<td type=Injected>
<td type=Removed>
<td type=Checklist>
</table>

</body>
</html>
