#! /usr/local/bin/tcsh -f

latex 05-03
bibtex 05-03
latex 05-03
latex 05-03
dvips 05-03.dvi -o 05-03.ps 
distill -resolution 2400 -colordownsample off -graydownsample off -monodownsample off -cmykimagestorgb off 05-03.ps
