#! /usr/local/bin/tcsh -f

latex 07-04
bibtex 07-04
latex 07-04
latex 07-04
dvips 07-04.dvi -o 07-04.ps 
#distill -resolution 2400 -colordownsample off -graydownsample off -monodownsample off -cmykimagestorgb off 07-04.ps

