#! /usr/local/bin/tcsh -f

latex 04-18
bibtex 04-18
latex 04-18
latex 04-18
dvips 04-18.dvi -o 04-18.ps 
distill -resolution 2400 -colordownsample off -graydownsample off -monodownsample off -cmykimagestorgb off 04-18.ps
