#! /usr/local/bin/tcsh -f

chmod 664 07-03.tex
latex 07-03
bibtex 07-03
latex 07-03
latex 07-03
dvips 07-03.dvi -o 07-03.ps 
distill -resolution 2400 -colordownsample off -graydownsample off -monodownsample off -cmykimagestorgb off 07-03.ps
