#! /usr/local/bin/tcsh -f

# Generate initial reference files (*.toc, *.aux, *.log, *.bbl, etc.)
latex thesis   
# Run bibtex to generate bibliography from reference files
bibtex thesis
# Now run latex twice more to include biblio stuff and resolve references and page numbers.
latex thesis
latex thesis
# Convert dvi file to postscript
dvips thesis.dvi -o thesis.ps 
# Convert postscript to pdf.
distill -resolution 2400 -colordownsample off thesis.ps
