<html>
<head>
<title>LEAP Data File</title>
</head>
<body>
<table border>
<tr>
<td>DRL Plain 1.0.0
<tr>
<th>CreateDate<th>DocID<th>FixTime<th>Location<th>Occurrences<th>DefectType<th>Severity<th>Description<th>Valid<th>UserCreated<th>UserFound<th>Injected<th>Removed<th>Checklist
<tr>
<td type=CreateDate>1998/06/19
<td type=DocID>intro.pdf
<td type=FixTime>
<td type=Location>p2 l9
<td type=Occurrences>
<td type=DefectType>30: Content
<td type=Severity>
<td type=Description>Might add: "In fact, this gave rise to the software engineering
adage that "You can't test in quality".
<td type=Valid>
<td type=UserCreated>
<td type=UserFound>
<td type=Injected>
<td type=Removed>
<td type=Checklist>
<tr>
<td type=CreateDate>1998/06/18
<td type=DocID>intro.pdf
<td type=FixTime>
<td type=Location>Section 1.4, 2nd paragraph
<td type=Occurrences>1
<td type=DefectType>30: Content
<td type=Severity>
<td type=Description>"By January 1997..." this paragraph starts abruptly. Usually when a
sentance is started with "by" I expect to have some sort of temporal
context already but here there isn't any.
<td type=Valid>
<td type=UserCreated>
<td type=UserFound>
<td type=Injected>
<td type=Removed>
<td type=Checklist>
<tr>
<td type=CreateDate>1998/06/18
<td type=DocID>intro.pdf
<td type=FixTime>
<td type=Location>Section 1.4, figure
<td type=Occurrences>1
<td type=DefectType>30: Content
<td type=Severity>
<td type=Description>The text inside the arrows is a little clipped
<td type=Valid>
<td type=UserCreated>
<td type=UserFound>
<td type=Injected>
<td type=Removed>
<td type=Checklist>
<tr>
<td type=CreateDate>1998/06/18
<td type=DocID>intro.pdf
<td type=FixTime>
<td type=Location>Section 1.7, 3rd para
<td type=Occurrences>1
<td type=DefectType>30: Content
<td type=Severity>
<td type=Description>I found the sentences about average age confusing and it required
a couple rereadings to figure out what was intended
<td type=Valid>
<td type=UserCreated>
<td type=UserFound>
<td type=Injected>
<td type=Removed>
<td type=Checklist>
<tr>
<td type=CreateDate>1998/06/19
<td type=DocID>intro.pdf
<td type=FixTime>
<td type=Location>p5 l20
<td type=Occurrences>1
<td type=DefectType>30: Content
<td type=Severity>
<td type=Description>I would add here:  'Note that although an "automated" PSP can
essentially automate all of the analysis stage calculations, there are 
limits to its ability to automate the collection stage work. The collection
stage is still quite "manual" in nature.
<td type=Valid>
<td type=UserCreated>
<td type=UserFound>
<td type=Injected>
<td type=Removed>
<td type=Checklist>
<tr>
<td type=CreateDate>1998/06/19
<td type=DocID>intro.pdf
<td type=FixTime>
<td type=Location>p6 l11
<td type=Occurrences>1
<td type=DefectType>30: Content
<td type=Severity>
<td type=Description>"using data collected from the next PSPclass taught by Dr. Johnson."
<td type=Valid>
<td type=UserCreated>
<td type=UserFound>
<td type=Injected>
<td type=Removed>
<td type=Checklist>
<tr>
<td type=CreateDate>1998/06/19
<td type=DocID>intro.pdf
<td type=FixTime>
<td type=Location>p7 l16
<td type=Occurrences>1
<td type=DefectType>30: Content
<td type=Severity>
<td type=Description>You might want to insert this at the start of Section 1.7:
"When this research project started, Dr. Johnson and I 
expected to find between 50 and 100 errors in the class data. 
This estimate was way off: we found 1539 errors.
<td type=Valid>
<td type=UserCreated>
<td type=UserFound>
<td type=Injected>
<td type=Removed>
<td type=Checklist>
<tr>
<td type=CreateDate>1998/06/19
<td type=DocID>intro.pdf
<td type=FixTime>
<td type=Location>p8 l11
<td type=Occurrences>1
<td type=DefectType>30: Content
<td type=Severity>
<td type=Description>Motivate this paragraph, perhaps as follows:
One might also hypothesize that these error simply constitute "noise"
and do not substantially impact upon the overall analysis results.
To test  this hypothesis, we recalculated some of the major
metrics using the (partially) corrected data.  We found....
<td type=Valid>
<td type=UserCreated>
<td type=UserFound>
<td type=Injected>
<td type=Removed>
<td type=Checklist>
<tr>
<td type=CreateDate>1998/06/18
<td type=DocID>intro.pdf
<td type=FixTime>
<td type=Location>section 1.1
<td type=Occurrences>1
<td type=DefectType>30: Content
<td type=Severity>
<td type=Description>This section begins rather abruptly. Perhaps a sentance
explaining what you are talking about and why?
<td type=Valid>
<td type=UserCreated>
<td type=UserFound>
<td type=Injected>
<td type=Removed>
<td type=Checklist>
<tr>
<td type=CreateDate>1998/06/19
<td type=DocID>intro.pdf
<td type=FixTime>
<td type=Location>p1 l1
<td type=Occurrences>1
<td type=DefectType>20:Organization
<td type=Severity>
<td type=Description>Suggestion: "Why is software quality important" for Section 1.1 title.
This motivates the accompanying text better.
<td type=Valid>
<td type=UserCreated>
<td type=UserFound>
<td type=Injected>
<td type=Removed>
<td type=Checklist>
<tr>
<td type=CreateDate>1998/06/18
<td type=DocID>intro.pdf
<td type=FixTime>
<td type=Location>p3 2nd para
<td type=Occurrences>1
<td type=DefectType>20:Organization
<td type=Severity>
<td type=Description>"Additionally, by tracking ..."  What does this have to do with
the goal of high-quality programs?  I agree that it is important,
but maybe it goes some where else.
<td type=Valid>
<td type=UserCreated>
<td type=UserFound>
<td type=Injected>
<td type=Removed>
<td type=Checklist>
<tr>
<td type=CreateDate>1998/06/19
<td type=DocID>intro.pdf
<td type=FixTime>
<td type=Location>p4
<td type=Occurrences>1
<td type=DefectType>20:Organization
<td type=Severity>
<td type=Description>Suggestion: entitle Section 1.4 "Motivation for this research"
to clarify what you are trying to motivate.
<td type=Valid>
<td type=UserCreated>
<td type=UserFound>
<td type=Injected>
<td type=Removed>
<td type=Checklist>
<tr>
<td type=CreateDate>1998/06/19
<td type=DocID>intro.pdf
<td type=FixTime>
<td type=Location>p4
<td type=Occurrences>1
<td type=DefectType>20:Organization
<td type=Severity>
<td type=Description>The caption for Figure 1.1 looks just like text. If the thesis
guidelines allow it, you may want to use \ls{1} and \em 
within captions in order to single space and italicize caption
text. This would make it clearly distinct from chapter text.
<td type=Valid>
<td type=UserCreated>
<td type=UserFound>
<td type=Injected>
<td type=Removed>
<td type=Checklist>
<tr>
<td type=CreateDate>1998/06/18
<td type=DocID>intro.pdf
<td type=FixTime>
<td type=Location>p5 2nd para
<td type=Occurrences>1
<td type=DefectType>20:Organization
<td type=Severity>
<td type=Description>I think this paragraph should be introduced somewhere else.
<td type=Valid>
<td type=UserCreated>
<td type=UserFound>
<td type=Injected>
<td type=Removed>
<td type=Checklist>
<tr>
<td type=CreateDate>1998/06/18
<td type=DocID>intro.pdf
<td type=FixTime>
<td type=Location>p6 1st para
<td type=Occurrences>1
<td type=DefectType>20:Organization
<td type=Severity>
<td type=Description>"These two problems..." sounds like a conclusion and not a 
hypothesis. 
<td type=Valid>
<td type=UserCreated>
<td type=UserFound>
<td type=Injected>
<td type=Removed>
<td type=Checklist>
<tr>
<td type=CreateDate>1998/06/19
<td type=DocID>intro.pdf
<td type=FixTime>
<td type=Location>p6 l1
<td type=Occurrences>1
<td type=DefectType>20:Organization
<td type=Severity>
<td type=Description>Rename 1.5 title: "Hypothesis of this research"
<td type=Valid>
<td type=UserCreated>
<td type=UserFound>
<td type=Injected>
<td type=Removed>
<td type=Checklist>
<tr>
<td type=CreateDate>1998/06/19
<td type=DocID>intro.pdf
<td type=FixTime>
<td type=Location>p3
<td type=Occurrences>7
<td type=DefectType>11: Passive voice
<td type=Severity>
<td type=Description>Lots of passive voice on this page. I have suggested corrections
on the hardcopy. In general, try to avoid passive voice.  I will note
other occurrences with a "p.v" on the hardcopy.
<td type=Valid>
<td type=UserCreated>
<td type=UserFound>
<td type=Injected>
<td type=Removed>
<td type=Checklist>
<tr>
<td type=CreateDate>1998/06/19
<td type=DocID>intro.pdf
<td type=FixTime>
<td type=Location>*
<td type=Occurrences>1
<td type=DefectType>10:Syntax
<td type=Severity>
<td type=Description>Avoid "we". Use "I".
<td type=Valid>
<td type=UserCreated>
<td type=UserFound>
<td type=Injected>
<td type=Removed>
<td type=Checklist>
<tr>
<td type=CreateDate>1998/06/18
<td type=DocID>intro.pdf
<td type=FixTime>
<td type=Location>Bibliography
<td type=Occurrences>1
<td type=DefectType>10:Syntax
<td type=Severity>
<td type=Description>[2] The title uses PSP but it isn't capialized. Probably a BibTeX error.
<td type=Valid>
<td type=UserCreated>
<td type=UserFound>
<td type=Injected>
<td type=Removed>
<td type=Checklist>
<tr>
<td type=CreateDate>1998/06/18
<td type=DocID>intro.pdf
<td type=FixTime>
<td type=Location>Sect 1.4
<td type=Occurrences>1
<td type=DefectType>10:Syntax
<td type=Severity>
<td type=Description>Why is this called motivation? Seems very jarring to me.
<td type=Valid>
<td type=UserCreated>
<td type=UserFound>
<td type=Injected>
<td type=Removed>
<td type=Checklist>
<tr>
<td type=CreateDate>1998/06/18
<td type=DocID>intro.pdf
<td type=FixTime>
<td type=Location>Section 1.3, 2nd sent
<td type=Occurrences>1
<td type=DefectType>10:Syntax
<td type=Severity>
<td type=Description>Maybe "each programmer performs a longitudinal experiment with
himself or herself as the subject" ?
<td type=Valid>
<td type=UserCreated>
<td type=UserFound>
<td type=Injected>
<td type=Removed>
<td type=Checklist>
<tr>
<td type=CreateDate>1998/06/18
<td type=DocID>intro.pdf
<td type=FixTime>
<td type=Location>Section 1.3, 3rd sent.
<td type=Occurrences>1
<td type=DefectType>10:Syntax
<td type=Severity>
<td type=Description>"Each new program written can..." "...and each additional program written..."
<td type=Valid>
<td type=UserCreated>
<td type=UserFound>
<td type=Injected>
<td type=Removed>
<td type=Checklist>
<tr>
<td type=CreateDate>1998/06/18
<td type=DocID>intro.pdf
<td type=FixTime>
<td type=Location>Section 1.6, 2nd para
<td type=Occurrences>1
<td type=DefectType>10:Syntax
<td type=Severity>
<td type=Description>First sentence awkward
<td type=Valid>
<td type=UserCreated>
<td type=UserFound>
<td type=Injected>
<td type=Removed>
<td type=Checklist>
<tr>
<td type=CreateDate>1998/06/19
<td type=DocID>intro.pdf
<td type=FixTime>
<td type=Location>p2 l3
<td type=Occurrences>1
<td type=DefectType>10:Syntax
<td type=Severity>
<td type=Description>"programmers have been" -> "the beginning of"
<td type=Valid>
<td type=UserCreated>
<td type=UserFound>
<td type=Injected>
<td type=Removed>
<td type=Checklist>
<tr>
<td type=CreateDate>1998/06/19
<td type=DocID>intro.pdf
<td type=FixTime>
<td type=Location>p2 l6
<td type=Occurrences>1
<td type=DefectType>10:Syntax
<td type=Severity>
<td type=Description>"At first" -> Into the 1960's
<td type=Valid>
<td type=UserCreated>
<td type=UserFound>
<td type=Injected>
<td type=Removed>
<td type=Checklist>
<tr>
<td type=CreateDate>1998/06/18
<td type=DocID>intro.pdf
<td type=FixTime>
<td type=Location>p2. 2nd para
<td type=Occurrences>1
<td type=DefectType>10:Syntax
<td type=Severity>
<td type=Description>"In the end, however, ..." very long sentence.
slightly confusing
<td type=Valid>
<td type=UserCreated>
<td type=UserFound>
<td type=Injected>
<td type=Removed>
<td type=Checklist>
<tr>
<td type=CreateDate>1998/06/18
<td type=DocID>intro.pdf
<td type=FixTime>
<td type=Location>p3 3rd para
<td type=Occurrences>1
<td type=DefectType>10:Syntax
<td type=Severity>
<td type=Description>Do you need the abreviations LOC and KLOC.  The defintintion 
for KLOC is confusing.
<td type=Valid>
<td type=UserCreated>
<td type=UserFound>
<td type=Injected>
<td type=Removed>
<td type=Checklist>
<tr>
<td type=CreateDate>1998/06/18
<td type=DocID>intro.pdf
<td type=FixTime>
<td type=Location>p4 2nd para
<td type=Occurrences>1
<td type=DefectType>10:Syntax
<td type=Severity>
<td type=Description>Very long complex sentence. "Although the general good..."
<td type=Valid>
<td type=UserCreated>
<td type=UserFound>
<td type=Injected>
<td type=Removed>
<td type=Checklist>
<tr>
<td type=CreateDate>1998/06/18
<td type=DocID>intro.pdf
<td type=FixTime>
<td type=Location>p6 3rd para
<td type=Occurrences>1
<td type=DefectType>10:Syntax
<td type=Severity>
<td type=Description>"(2) the addition of" is awkward.  Maybe "added four" instead.
<td type=Valid>
<td type=UserCreated>
<td type=UserFound>
<td type=Injected>
<td type=Removed>
<td type=Checklist>
<tr>
<td type=CreateDate>1998/06/18
<td type=DocID>intro.pdf
<td type=FixTime>
<td type=Location>p6,7
<td type=Occurrences>1
<td type=DefectType>10:Syntax
<td type=Severity>
<td type=Description>The term mistakes is used then errors.  Are mistakes erorrs or
is there some distinction between mistakes and errors?
<td type=Valid>
<td type=UserCreated>
<td type=UserFound>
<td type=Injected>
<td type=Removed>
<td type=Checklist>
<tr>
<td type=CreateDate>
<td type=DocID>honu/leap
<td type=FixTime>
<td type=Location>
<td type=Occurrences>
<td type=DefectType>
<td type=Severity>A-Critical
<td type=Description>window close event on Command tool needs to be trapped and then you check for unsaved tables.
<td type=Valid>
<td type=UserCreated>
<td type=UserFound>
<td type=Injected>
<td type=Removed>
<td type=Checklist>
<tr>
<td type=CreateDate>1998/06/19
<td type=DocID>honu
<td type=FixTime>
<td type=Location>
<td type=Occurrences>
<td type=DefectType>
<td type=Severity>A-Critical
<td type=Description>I think the "Table" menu should be renamed to "File". All of its interior selections are similar to what normally appears in a file menu, and it does concern itself with file IO.
<td type=Valid>T
<td type=UserCreated>T
<td type=UserFound>T
<td type=Injected>
<td type=Removed>
<td type=Checklist>
<tr>
<td type=CreateDate>1998/06/19
<td type=DocID>honu
<td type=FixTime>
<td type=Location>
<td type=Occurrences>
<td type=DefectType>
<td type=Severity>A-Critical
<td type=Description>When I hit "Save" from the table menu on a table that has already been saved, it does not default the file name to the name I used previously, 
and it asks me if I want to overwrite. In effect, it operates as "SaveAs" rather than as "Save".
<SimpleSave>
<td type=Valid>T
<td type=UserCreated>T
<td type=UserFound>T
<td type=Injected>
<td type=Removed>
<td type=Checklist>
<tr>
<td type=CreateDate>1998/06/19
<td type=DocID>honu
<td type=FixTime>
<td type=Location>
<td type=Occurrences>
<td type=DefectType>
<td type=Severity>A-Critical
<td type=Description>The general "Save" dialog from the "Table" menu seems to do exactly the right thing: 
it brings up a nice browsable dialog and saves only the defect data.  
How do we make this the "normal" save dialog?
<SimpleSwing>
<td type=Valid>T
<td type=UserCreated>T
<td type=UserFound>T
<td type=Injected>
<td type=Removed>
<td type=Checklist>
<tr>
<td type=CreateDate>1998/06/17
<td type=DocID>leaptool
<td type=FixTime>
<td type=Location>save/saveAs dialog box
<td type=Occurrences>
<td type=DefectType>
<td type=Severity>A-Critical
<td type=Description>A bad file name is not handled well. The tool seems to "Freeze".
<td type=Valid>T
<td type=UserCreated>T
<td type=UserFound>T
<td type=Injected>
<td type=Removed>
<td type=Checklist>
<tr>
<td type=CreateDate>1998/06/17
<td type=DocID>leaptool
<td type=FixTime>
<td type=Location>Save/saveAs dialog box
<td type=Occurrences>
<td type=DefectType>
<td type=Severity>A-Critical
<td type=Description>Can there be a "browse" button so that people can point and click to the file and/or directory?
<td type=Valid>T
<td type=UserCreated>T
<td type=UserFound>T
<td type=Injected>
<td type=Removed>
<td type=Checklist>
<tr>
<td type=CreateDate>1998/06/18
<td type=DocID>RunLeap
<td type=FixTime>
<td type=Location>Cell Editor
<td type=Occurrences>1
<td type=DefectType>20:Functionality
<td type=Severity>A-Critical
<td type=Description>Can't find a way to commit an edit without using the mouse. Return,
Tab, and the arrow keys all don't do it.
<Need a help page on navigation in JClass table>
<td type=Valid>
<td type=UserCreated>
<td type=UserFound>
<td type=Injected>
<td type=Removed>
<td type=Checklist>
<tr>
<td type=CreateDate>1998/06/18
<td type=DocID>RunLeap
<td type=FixTime>
<td type=Location>Save Dialog
<td type=Occurrences>1
<td type=DefectType>10:Usability
<td type=Severity>A-Critical
<td type=Description>Complicated. Not clear what I should do to just save my new defects.
Will having the other tables checked overwrite the defaults? 
<SimpleSave>
<td type=Valid>
<td type=UserCreated>
<td type=UserFound>
<td type=Injected>
<td type=Removed>
<td type=Checklist>
<tr>
<td type=CreateDate>
<td type=DocID>honu
<td type=FixTime>
<td type=Location>
<td type=Occurrences>
<td type=DefectType>
<td type=Severity>A-Critical
<td type=Description>Proposed simplesave button/menu action in a table-specific tool:
  1. There is a save button whose purpose is to save out the items in that particular table.
       and any other data that came from that file. but no new stuff from a different table.
  2. This button works only when (a) no files have been loaded or (b) exactly one file has been loaded.
  3.  We catch window close and check dirty bits for each table which have been set kludgily.

We rename current save button behavior as Multi-Table Save and put it as a menu item.
<td type=Valid>
<td type=UserCreated>
<td type=UserFound>
<td type=Injected>
<td type=Removed>
<td type=Checklist>
<tr>
<td type=CreateDate>
<td type=DocID>honu/leap
<td type=FixTime>
<td type=Location>
<td type=Occurrences>
<td type=DefectType>
<td type=Severity>A-Critical
<td type=Description>When I click on "About LEAP", I don't get a distribution version number.
<td type=Valid>
<td type=UserCreated>
<td type=UserFound>
<td type=Injected>
<td type=Removed>
<td type=Checklist>
<tr>
<td type=CreateDate>
<td type=DocID>honu
<td type=FixTime>
<td type=Location>
<td type=Occurrences>
<td type=DefectType>
<td type=Severity>A-Critical
<td type=Description>Reduce size of filtering panel.
<td type=Valid>
<td type=UserCreated>
<td type=UserFound>
<td type=Injected>
<td type=Removed>
<td type=Checklist>
<tr>
<td type=CreateDate>
<td type=DocID>honu
<td type=FixTime>
<td type=Location>
<td type=Occurrences>
<td type=DefectType>
<td type=Severity>B-Important
<td type=Description>Would be nice to have a mode where the height of each cell
(Like description) is automatically sized to the number of 
lines in its contents. In other words, so you can see everything
automatically. If this is a one line change, we ought to do it 
for the next release, which is why I'm making it a B.
<td type=Valid>
<td type=UserCreated>
<td type=UserFound>
<td type=Injected>
<td type=Removed>
<td type=Checklist>
<tr>
<td type=CreateDate>
<td type=DocID>
<td type=FixTime>
<td type=Location>
<td type=Occurrences>
<td type=DefectType>
<td type=Severity>B-Important
<td type=Description>If you click on a column to sort it without commiting the current edit in a cell, 
it is lost. Column sort needs to commit the current edit if any.
<td type=Valid>
<td type=UserCreated>
<td type=UserFound>
<td type=Injected>
<td type=Removed>
<td type=Checklist>
<tr>
<td type=CreateDate>1998/06/19
<td type=DocID>honu
<td type=FixTime>
<td type=Location>
<td type=Occurrences>
<td type=DefectType>
<td type=Severity>B-Important
<td type=Description>Need a one-click auto default across column mode.
If an "important" column like docID or date gets hidden, does it still get filled out automatically? 
Can we add behavior to certain distinguished columns to guarantee they get filled in, regardless of whether they're shown or not (or clicked on or not).


<td type=Valid>T
<td type=UserCreated>T
<td type=UserFound>T
<td type=Injected>
<td type=Removed>
<td type=Checklist>
<tr>
<td type=CreateDate>1998/06/17
<td type=DocID>leaptool
<td type=FixTime>
<td type=Location>email dialog box
<td type=Occurrences>
<td type=DefectType>
<td type=Severity>B-Important
<td type=Description>The mail server value does not seem to be saved between sessions.
<td type=Valid>T
<td type=UserCreated>T
<td type=UserFound>T
<td type=Injected>
<td type=Removed>
<td type=Checklist>
<tr>
<td type=CreateDate>1998/06/17
<td type=DocID>leaptool
<td type=FixTime>
<td type=Location>last field
<td type=Occurrences>
<td type=DefectType>
<td type=Severity>B-Important
<td type=Description>When you enter text into a field but don't tab out of it before saving, that text is lost. This is a significant usability error...
<td type=Valid>T
<td type=UserCreated>T
<td type=UserFound>T
<td type=Injected>
<td type=Removed>
<td type=Checklist>
<tr>
<td type=CreateDate>1998/06/17
<td type=DocID>leaptool
<td type=FixTime>
<td type=Location>Save/saveAs dialog box
<td type=Occurrences>
<td type=DefectType>
<td type=Severity>B-Important
<td type=Description>After a request to overwrite the file is responded Y, the save/saveas dosen't go away. It's like it didn't do anything (although it did).
<td type=Valid>T
<td type=UserCreated>T
<td type=UserFound>T
<td type=Injected>
<td type=Removed>
<td type=Checklist>
<tr>
<td type=CreateDate>1998/06/18
<td type=DocID>RunLeap
<td type=FixTime>
<td type=Location>Cell Editor
<td type=Occurrences>1
<td type=DefectType>30:Bug
<td type=Severity>C-Swing/JClass
<td type=Description>Try to resize the window while editing a cell. The editing changes
are blown away! 
<td type=Valid>
<td type=UserCreated>
<td type=UserFound>
<td type=Injected>
<td type=Removed>
<td type=Checklist>
<tr>
<td type=CreateDate>1998/06/18
<td type=DocID>RunLeap
<td type=FixTime>
<td type=Location>Defect Type col
<td type=Occurrences>1
<td type=DefectType>10:Usability
<td type=Severity>C-Swing/JClass
<td type=Description>When displayed the cell is aligned top left, but when editing it is
aligned middle left.
<td type=Valid>
<td type=UserCreated>
<td type=UserFound>
<td type=Injected>
<td type=Removed>
<td type=Checklist>
<tr>
<td type=CreateDate>1998/06/18
<td type=DocID>RunLeap
<td type=FixTime>
<td type=Location>Description Editor
<td type=Occurrences>1
<td type=DefectType>10:Usability
<td type=Severity>C-Swing/JClass
<td type=Description>Try typing off the end of the description cell. Everything gets funky
and text is displayed willy-nilly. If you insert a CR to wrap the line
the new text isn't properly redrawn. It desperately needs to be word
wrapped.
<td type=Valid>
<td type=UserCreated>
<td type=UserFound>
<td type=Injected>
<td type=Removed>
<td type=Checklist>
<tr>
<td type=CreateDate>
<td type=DocID>honu
<td type=FixTime>
<td type=Location>
<td type=Occurrences>
<td type=DefectType>
<td type=Severity>C-Swing/JClass
<td type=Description>In-tool help is bogus. Will be fixed when JavaHelp API is released.
<td type=Valid>
<td type=UserCreated>
<td type=UserFound>
<td type=Injected>
<td type=Removed>
<td type=Checklist>
<tr>
<td type=CreateDate>1998/06/19
<td type=DocID>leap
<td type=FixTime>
<td type=Location>
<td type=Occurrences>
<td type=DefectType>
<td type=Severity>C-Swing/Jclass
<td type=Description>Vanilla viewer tables need to be clicked on to be seen when first coming up.
<td type=Valid>T
<td type=UserCreated>T
<td type=UserFound>T
<td type=Injected>
<td type=Removed>
<td type=Checklist>
<tr>
<td type=CreateDate>1998/06/19
<td type=DocID>honu
<td type=FixTime>
<td type=Location>
<td type=Occurrences>
<td type=DefectType>
<td type=Severity>C-Swing/Jclass
<td type=Description>After showing/hiding columns, the table does not get resized.
<td type=Valid>T
<td type=UserCreated>T
<td type=UserFound>T
<td type=Injected>
<td type=Removed>
<td type=Checklist>
<tr>
<td type=CreateDate>
<td type=DocID>honu/leap
<td type=FixTime>
<td type=Location>
<td type=Occurrences>
<td type=DefectType>
<td type=Severity>D-Future
<td type=Description>Cannot chart by Severity!
<td type=Valid>
<td type=UserCreated>
<td type=UserFound>
<td type=Injected>
<td type=Removed>
<td type=Checklist>
<tr>
<td type=CreateDate>
<td type=DocID>honu
<td type=FixTime>
<td type=Location>
<td type=Occurrences>
<td type=DefectType>
<td type=Severity>D-Future
<td type=Description>When editing a cell, can the contents be put in the upper right hand corner
and not in the center?  Would be nicer.
<td type=Valid>
<td type=UserCreated>
<td type=UserFound>
<td type=Injected>
<td type=Removed>
<td type=Checklist>
<tr>
<td type=CreateDate>1998/06/19
<td type=DocID>honu
<td type=FixTime>
<td type=Location>
<td type=Occurrences>
<td type=DefectType>
<td type=Severity>D-Future
<td type=Description>I would default the location field value too.
<td type=Valid>T
<td type=UserCreated>T
<td type=UserFound>T
<td type=Injected>
<td type=Removed>
<td type=Checklist>
<tr>
<td type=CreateDate>1998/06/19
<td type=DocID>honu
<td type=FixTime>
<td type=Location>
<td type=Occurrences>
<td type=DefectType>
<td type=Severity>D-Future
<td type=Description>Can we tell the save dialog box for just defects to use a default extension of .drl?
<td type=Valid>T
<td type=UserCreated>T
<td type=UserFound>T
<td type=Injected>
<td type=Removed>
<td type=Checklist>
<tr>
<td type=CreateDate>1998/06/19
<td type=DocID>honu
<td type=FixTime>
<td type=Location>
<td type=Occurrences>
<td type=DefectType>
<td type=Severity>D-Future
<td type=Description>Remove help line at bottom of honu window (help target)
<td type=Valid>T
<td type=UserCreated>T
<td type=UserFound>T
<td type=Injected>
<td type=Removed>
<td type=Checklist>
<tr>
<td type=CreateDate>1998/06/19
<td type=DocID>honu
<td type=FixTime>
<td type=Location>
<td type=Occurrences>
<td type=DefectType>
<td type=Severity>D-Future
<td type=Description>Can we safely eliminate the header panel? I don't see any benefits of it at this point.
<td type=Valid>T
<td type=UserCreated>T
<td type=UserFound>T
<td type=Injected>
<td type=Removed>
<td type=Checklist>
<tr>
<td type=CreateDate>1998/06/19
<td type=DocID>honu
<td type=FixTime>
<td type=Location>
<td type=Occurrences>
<td type=DefectType>
<td type=Severity>D-Future
<td type=Description>Can additions to the severity menu result in additions to the popup menu at run-time?
<td type=Valid>T
<td type=UserCreated>T
<td type=UserFound>T
<td type=Injected>
<td type=Removed>
<td type=Checklist>
<tr>
<td type=CreateDate>1998/06/17
<td type=DocID>leaptool
<td type=FixTime>
<td type=Location>honu pop up menus 
<td type=Occurrences>
<td type=DefectType>
<td type=Severity>D-Future
<td type=Description>When I add a new defect type, it doesn't get added to the honu popup menus. How can I force them to get updated?
<td type=Valid>T
<td type=UserCreated>T
<td type=UserFound>T
<td type=Injected>
<td type=Removed>
<td type=Checklist>
<tr>
<td type=CreateDate>1998/06/17
<td type=DocID>leaptool
<td type=FixTime>
<td type=Location>-honu command line argument
<td type=Occurrences>
<td type=DefectType>
<td type=Severity>D-Future
<td type=Description>It does bring up honu, but honu is *behind* the LeapTool window. Can -honu at least bring up Honu in *front* of the LeapTool?
<td type=Valid>T
<td type=UserCreated>T
<td type=UserFound>T
<td type=Injected>
<td type=Removed>
<td type=Checklist>
<tr>
<td type=CreateDate>1998/06/17
<td type=DocID>leaptool
<td type=FixTime>
<td type=Location>Honu header panel
<td type=Occurrences>
<td type=DefectType>
<td type=Severity>D-Future
<td type=Description>If I edit a docID in the docID vanilla viewer, then switch back to Honu, the header panel does not reflect the update.
<td type=Valid>T
<td type=UserCreated>T
<td type=UserFound>T
<td type=Injected>
<td type=Removed>
<td type=Checklist>
<tr>
<td type=CreateDate>1998/06/17
<td type=DocID>leaptool
<td type=FixTime>
<td type=Location>Honu header panel
<td type=Occurrences>
<td type=DefectType>
<td type=Severity>D-Future
<td type=Description>Project and doctype popups don't work.
<td type=Valid>T
<td type=UserCreated>T
<td type=UserFound>T
<td type=Injected>
<td type=Removed>
<td type=Checklist>
<tr>
<td type=CreateDate>1998/06/17
<td type=DocID>leaptool
<td type=FixTime>
<td type=Location>Save/SaveAs dialog box
<td type=Occurrences>
<td type=DefectType>
<td type=Severity>D-Future
<td type=Description>When one of the file names is long, then the appearance gets weird (the two column format is not preserved.
<td type=Valid>T
<td type=UserCreated>T
<td type=UserFound>T
<td type=Injected>
<td type=Removed>
<td type=Checklist>
<tr>
<td type=CreateDate>1998/06/18
<td type=DocID>RunLeap
<td type=FixTime>
<td type=Location>Severity column
<td type=Occurrences>1
<td type=DefectType>10:Usability
<td type=Severity>D-Future
<td type=Description>The severity column header is truncated with the default window size.
<Change percentages on field widths>
<td type=Valid>
<td type=UserCreated>
<td type=UserFound>
<td type=Injected>
<td type=Removed>
<td type=Checklist>
<tr>
<td type=CreateDate>
<td type=DocID>honu/leap
<td type=FixTime>
<td type=Location>
<td type=Occurrences>
<td type=DefectType>
<td type=Severity>D-Future
<td type=Description>Would be nice to have an "meta-Q" function that would word wrap
the contents of a description field. This would enable Defmacs 
comments to be imported into the Java stuff more easily.
<td type=Valid>
<td type=UserCreated>
<td type=UserFound>
<td type=Injected>
<td type=Removed>
<td type=Checklist>
<tr>
<td type=CreateDate>
<td type=DocID>honu/leap
<td type=FixTime>
<td type=Location>
<td type=Occurrences>
<td type=DefectType>
<td type=Severity>D-Future
<td type=Description>Would be nice to have a printing function that would generate a nice
HTML report or something displaying the current displayed columns
(or the current chart).  Perhaps we need a "reportlet" API (like doclet and applet)
so that people can easily get data out of LEAP. Something for a fall student
project.
<td type=Valid>
<td type=UserCreated>
<td type=UserFound>
<td type=Injected>
<td type=Removed>
<td type=Checklist>
<tr>
<td type=CreateDate>
<td type=DocID>honu
<td type=FixTime>
<td type=Location>
<td type=Occurrences>
<td type=DefectType>
<td type=Severity>D-Future
<td type=Description>Provide a way to save out the filtered (i.e. displayed) defects.
<td type=Valid>
<td type=UserCreated>
<td type=UserFound>
<td type=Injected>
<td type=Removed>
<td type=Checklist>
<tr>
<td type=CreateDate>
<td type=DocID>honu
<td type=FixTime>
<td type=Location>
<td type=Occurrences>
<td type=DefectType>
<td type=Severity>D-Important
<td type=Description>Rows should have a read-only index number for ease of reference
during group discussions.
<td type=Valid>
<td type=UserCreated>
<td type=UserFound>
<td type=Injected>
<td type=Removed>
<td type=Checklist>
<tr>
<td type=CreateDate>1998/06/17
<td type=DocID>leaptool
<td type=FixTime>
<td type=Location>Honu header panel
<td type=Occurrences>
<td type=DefectType>
<td type=Severity>E-Disregard
<td type=Description>Size does not show up for the docID. (Is this a known problem? I forget.)
<td type=Valid>T
<td type=UserCreated>T
<td type=UserFound>T
<td type=Injected>
<td type=Removed>
<td type=Checklist>
<tr>
<td type=CreateDate>1998/06/17
<td type=DocID>leaptool
<td type=FixTime>
<td type=Location>save/saveAs dialog box
<td type=Occurrences>
<td type=DefectType>
<td type=Severity>E-Disregard
<td type=Description>Shouldn't the list boxes display all the possible files? Maybe not?
<td type=Valid>T
<td type=UserCreated>T
<td type=UserFound>T
<td type=Injected>
<td type=Removed>
<td type=Checklist>
<tr>
<td type=CreateDate>1998/06/18
<td type=DocID>RunLeap
<td type=FixTime>
<td type=Location>Severity column
<td type=Occurrences>1
<td type=DefectType>10:Usability
<td type=Severity>E-Disregard
<td type=Description>What are we supposed to put here? No guidance...
<td type=Valid>
<td type=UserCreated>
<td type=UserFound>
<td type=Injected>
<td type=Removed>
<td type=Checklist>
<tr>
<td type=CreateDate>1998/06/18
<td type=DocID>RunLeap
<td type=FixTime>
<td type=Location>Table grid
<td type=Occurrences>1
<td type=DefectType>10:Usability
<td type=Severity>E-Disregard
<td type=Description>Each row seems strangely tall, so the Date and DocID fields
look lost in a big cell. I guess this is so more of the description
field can show at once.
<td type=Valid>
<td type=UserCreated>
<td type=UserFound>
<td type=Injected>
<td type=Removed>
<td type=Checklist>
<tr>
<td type=CreateDate>1998/06/18
<td type=DocID>intro.pdf
<td type=FixTime>
<td type=Location>p3 3rd para
<td type=Occurrences>1
<td type=DefectType>10:Syntax
<td type=Severity>low
<td type=Description>"On a simple level, when ..." sounds awkward to me.
<td type=Valid>
<td type=UserCreated>
<td type=UserFound>
<td type=Injected>
<td type=Removed>
<td type=Checklist>
<tr>
<td type=CreateDate>
<td type=DocID>honu
<td type=FixTime>
<td type=Location>
<td type=Occurrences>
<td type=DefectType>
<td type=Severity>C-Swing/Jclass
<td type=Description>On windows, after a save, a file folder window is pushed in front of the toolkit. Does not occur 
in Solaris. Go Figure.
<td type=Valid>
<td type=UserCreated>
<td type=UserFound>
<td type=Injected>
<td type=Removed>
<td type=Checklist>
</table>

</body>
</html>
