<html>
<head>
<title>LEAP Data File</title>
</head>
<body>
<table border>
<tr>
<td>DRL Plain 1.0.0
<tr>
<th>CreateDate<th>DocID<th>FixTime<th>Location<th>Occurrences<th>DefectType<th>Severity<th>Description<th>Valid<th>UserCreated<th>UserFound<th>Injected<th>Removed<th>Checklist
<tr>
<td type=CreateDate>1998/06/17
<td type=DocID>leaptool
<td type=FixTime>
<td type=Location>Save/saveAs dialog box
<td type=Occurrences>
<td type=DefectType>
<td type=Severity>
<td type=Description>Can there be a "browse" button so that people can point and click to the file and/or directory?
<td type=Valid>T
<td type=UserCreated>T
<td type=UserFound>T
<td type=Injected>
<td type=Removed>
<td type=Checklist>
<tr>
<td type=CreateDate>1998/06/17
<td type=DocID>leaptool
<td type=FixTime>
<td type=Location>save/saveAs dialog box
<td type=Occurrences>
<td type=DefectType>
<td type=Severity>
<td type=Description>A bad file name is not handled well. The tool seems to "Freeze".
<td type=Valid>T
<td type=UserCreated>T
<td type=UserFound>T
<td type=Injected>
<td type=Removed>
<td type=Checklist>
<tr>
<td type=CreateDate>1998/06/17
<td type=DocID>leaptool
<td type=FixTime>
<td type=Location>save/saveAs dialog box
<td type=Occurrences>
<td type=DefectType>
<td type=Severity>
<td type=Description>Shouldn't the list boxes display all the possible files? Maybe not?
<td type=Valid>T
<td type=UserCreated>T
<td type=UserFound>T
<td type=Injected>
<td type=Removed>
<td type=Checklist>
<tr>
<td type=CreateDate>1998/06/17
<td type=DocID>leaptool
<td type=FixTime>
<td type=Location>Save/saveAs dialog box
<td type=Occurrences>
<td type=DefectType>
<td type=Severity>
<td type=Description>After a request to overwrite the file is responded Y, the save/saveas dosen't go away. It's like it didn't do anything (although it did).
<td type=Valid>T
<td type=UserCreated>T
<td type=UserFound>T
<td type=Injected>
<td type=Removed>
<td type=Checklist>
<tr>
<td type=CreateDate>1998/06/17
<td type=DocID>leaptool
<td type=FixTime>
<td type=Location>Honu header panel
<td type=Occurrences>
<td type=DefectType>
<td type=Severity>
<td type=Description>Size does not show up for the docID. (Is this a known problem? I forget.)
<td type=Valid>T
<td type=UserCreated>T
<td type=UserFound>T
<td type=Injected>
<td type=Removed>
<td type=Checklist>
<tr>
<td type=CreateDate>1998/06/17
<td type=DocID>leaptool
<td type=FixTime>
<td type=Location>Save/SaveAs dialog box
<td type=Occurrences>
<td type=DefectType>
<td type=Severity>
<td type=Description>When one of the file names is long, then the appearance gets weird (the two column format is not preserved.
<td type=Valid>T
<td type=UserCreated>T
<td type=UserFound>T
<td type=Injected>
<td type=Removed>
<td type=Checklist>
<tr>
<td type=CreateDate>1998/06/17
<td type=DocID>leaptool
<td type=FixTime>
<td type=Location>Honu header panel
<td type=Occurrences>
<td type=DefectType>
<td type=Severity>
<td type=Description>Project and doctype popups don't work.
<td type=Valid>T
<td type=UserCreated>T
<td type=UserFound>T
<td type=Injected>
<td type=Removed>
<td type=Checklist>
<tr>
<td type=CreateDate>1998/06/17
<td type=DocID>leaptool
<td type=FixTime>
<td type=Location>last field
<td type=Occurrences>
<td type=DefectType>
<td type=Severity>
<td type=Description>When you enter text into a field but don't tab out of it before saving, that text is lost. This is a significant usability error...
<td type=Valid>T
<td type=UserCreated>T
<td type=UserFound>T
<td type=Injected>
<td type=Removed>
<td type=Checklist>
<tr>
<td type=CreateDate>1998/06/17
<td type=DocID>leaptool
<td type=FixTime>
<td type=Location>Honu header panel
<td type=Occurrences>
<td type=DefectType>
<td type=Severity>
<td type=Description>If I edit a docID in the docID vanilla viewer, then switch back to Honu, the header panel does not reflect the update.
<td type=Valid>T
<td type=UserCreated>T
<td type=UserFound>T
<td type=Injected>
<td type=Removed>
<td type=Checklist>
<tr>
<td type=CreateDate>1998/06/17
<td type=DocID>leaptool
<td type=FixTime>
<td type=Location>-honu command line argument
<td type=Occurrences>
<td type=DefectType>
<td type=Severity>
<td type=Description>It does bring up honu, but honu is *behind* the LeapTool window. Can -honu at least bring up Honu in *front* of the LeapTool?
<td type=Valid>T
<td type=UserCreated>T
<td type=UserFound>T
<td type=Injected>
<td type=Removed>
<td type=Checklist>
<tr>
<td type=CreateDate>1998/06/17
<td type=DocID>leaptool
<td type=FixTime>
<td type=Location>email dialog box
<td type=Occurrences>
<td type=DefectType>
<td type=Severity>
<td type=Description>The mail server value does not seem to be saved between sessions.
<td type=Valid>T
<td type=UserCreated>T
<td type=UserFound>T
<td type=Injected>
<td type=Removed>
<td type=Checklist>
<tr>
<td type=CreateDate>1998/06/17
<td type=DocID>leaptool
<td type=FixTime>
<td type=Location>honu pop up menus 
<td type=Occurrences>
<td type=DefectType>
<td type=Severity>
<td type=Description>When I add a new defect type, it doesn't get added to the honu popup menus. How can I force them to get updated?
<td type=Valid>T
<td type=UserCreated>T
<td type=UserFound>T
<td type=Injected>
<td type=Removed>
<td type=Checklist>
<tr>
<td type=CreateDate>1998/06/19
<td type=DocID>honu
<td type=FixTime>
<td type=Location>
<td type=Occurrences>
<td type=DefectType>
<td type=Severity>
<td type=Description>If an "important" column like docID or date gets hidden, does it still get filled out automatically? Can we add behavior to certain distinguished columns to guarantee they get filled in, regardless of whether they're shown or not (or clicked on or not).
<td type=Valid>T
<td type=UserCreated>T
<td type=UserFound>T
<td type=Injected>
<td type=Removed>
<td type=Checklist>
<tr>
<td type=CreateDate>1998/06/19
<td type=DocID>honu
<td type=FixTime>
<td type=Location>
<td type=Occurrences>
<td type=DefectType>
<td type=Severity>
<td type=Description>
<td type=Valid>T
<td type=UserCreated>T
<td type=UserFound>T
<td type=Injected>
<td type=Removed>
<td type=Checklist>
<tr>
<td type=CreateDate>1998/06/19
<td type=DocID>honu
<td type=FixTime>
<td type=Location>
<td type=Occurrences>
<td type=DefectType>
<td type=Severity>
<td type=Description>After showing/hiding columns, the table does not get resized.
<td type=Valid>T
<td type=UserCreated>T
<td type=UserFound>T
<td type=Injected>
<td type=Removed>
<td type=Checklist>
<tr>
<td type=CreateDate>1998/06/19
<td type=DocID>leap
<td type=FixTime>
<td type=Location>
<td type=Occurrences>
<td type=DefectType>
<td type=Severity>
<td type=Description>Vanilla viewer tables need to be clicked on to be seen when first coming up.
<td type=Valid>T
<td type=UserCreated>T
<td type=UserFound>T
<td type=Injected>
<td type=Removed>
<td type=Checklist>
<tr>
<td type=CreateDate>1998/06/19
<td type=DocID>honu
<td type=FixTime>
<td type=Location>
<td type=Occurrences>
<td type=DefectType>
<td type=Severity>
<td type=Description>Can we safely eliminate the header panel? I don't see any benefits of it at this point.
<td type=Valid>T
<td type=UserCreated>T
<td type=UserFound>T
<td type=Injected>
<td type=Removed>
<td type=Checklist>
<tr>
<td type=CreateDate>1998/06/19
<td type=DocID>honu
<td type=FixTime>
<td type=Location>
<td type=Occurrences>
<td type=DefectType>
<td type=Severity>
<td type=Description>
<td type=Valid>T
<td type=UserCreated>T
<td type=UserFound>T
<td type=Injected>
<td type=Removed>
<td type=Checklist>
<tr>
<td type=CreateDate>1998/06/19
<td type=DocID>honu
<td type=FixTime>
<td type=Location>
<td type=Occurrences>
<td type=DefectType>
<td type=Severity>
<td type=Description>The general "Save" dialog from the "Table" menu seems to do exactly the right thing: it brings up a nice browsable dialog and saves only the defect data.  How do we make this the "normal" save dialog?
<td type=Valid>T
<td type=UserCreated>T
<td type=UserFound>T
<td type=Injected>
<td type=Removed>
<td type=Checklist>
<tr>
<td type=CreateDate>1998/06/19
<td type=DocID>honu
<td type=FixTime>
<td type=Location>
<td type=Occurrences>
<td type=DefectType>
<td type=Severity>
<td type=Description>Can we tell the save dialog box for just defects to use a default extension of .drl?
<td type=Valid>T
<td type=UserCreated>T
<td type=UserFound>T
<td type=Injected>
<td type=Removed>
<td type=Checklist>
<tr>
<td type=CreateDate>1998/06/19
<td type=DocID>honu
<td type=FixTime>
<td type=Location>
<td type=Occurrences>
<td type=DefectType>
<td type=Severity>
<td type=Description>I would default the location field value too.
<td type=Valid>T
<td type=UserCreated>T
<td type=UserFound>T
<td type=Injected>
<td type=Removed>
<td type=Checklist>
<tr>
<td type=CreateDate>1998/06/19
<td type=DocID>honu
<td type=FixTime>
<td type=Location>
<td type=Occurrences>
<td type=DefectType>
<td type=Severity>
<td type=Description>When I hit "Save" from the table menu on a table that has already been saved, it does not default the file name to the name I used previously, and it asks me if I want to overwrite. In effect, it operates as "SaveAs" rather than as "Save".
<td type=Valid>T
<td type=UserCreated>T
<td type=UserFound>T
<td type=Injected>
<td type=Removed>
<td type=Checklist>
<tr>
<td type=CreateDate>1998/06/19
<td type=DocID>honu
<td type=FixTime>
<td type=Location>
<td type=Occurrences>
<td type=DefectType>
<td type=Severity>
<td type=Description>I think the "Table" menu should be renamed to "File". All of its interior selections are similar to what normally appears in a file menu, and it does concern itself with file IO.
<td type=Valid>T
<td type=UserCreated>T
<td type=UserFound>T
<td type=Injected>
<td type=Removed>
<td type=Checklist>
</table>

</body>
</html>
