<html>
<head>
<title>LEAP Data File</title>
</head>
<body>
<table border>
<tr>
<td>DRL Plain 1.0.0
<tr>
<th>CreateDate<th>DocID<th>FixTime<th>Location<th>Occurrences<th>DefectType<th>Severity<th>Description<th>Valid<th>UserCreated<th>UserFound<th>Injected<th>Removed<th>Checklist
<tr>
<td type=CreateDate>1998/06/18
<td type=DocID>intro.pdf
<td type=FixTime>
<td type=Location>p2. 2nd para
<td type=Occurrences>1
<td type=DefectType>10:Syntax
<td type=Severity>
<td type=Description>"In the end, however, ..." very long sentence.
slightly confusing
<td type=Valid>
<td type=UserCreated>
<td type=UserFound>
<td type=Injected>
<td type=Removed>
<td type=Checklist>
<tr>
<td type=CreateDate>1998/06/18
<td type=DocID>intro.pdf
<td type=FixTime>
<td type=Location>p3 2nd para
<td type=Occurrences>1
<td type=DefectType>20:Organization
<td type=Severity>
<td type=Description>"Additionally, by tracking ..."  What does this have to do with
the goal of high-quality programs?  I agree that it is important,
but maybe it goes some where else.
<td type=Valid>
<td type=UserCreated>
<td type=UserFound>
<td type=Injected>
<td type=Removed>
<td type=Checklist>
<tr>
<td type=CreateDate>1998/06/18
<td type=DocID>intro.pdf
<td type=FixTime>
<td type=Location>p3 3rd para
<td type=Occurrences>1
<td type=DefectType>10:Syntax
<td type=Severity>low
<td type=Description>"On a simple level, when ..." sounds awkward to me.
<td type=Valid>
<td type=UserCreated>
<td type=UserFound>
<td type=Injected>
<td type=Removed>
<td type=Checklist>
<tr>
<td type=CreateDate>1998/06/18
<td type=DocID>intro.pdf
<td type=FixTime>
<td type=Location>p3 3rd para
<td type=Occurrences>1
<td type=DefectType>10:Syntax
<td type=Severity>
<td type=Description>Do you need the abreviations LOC and KLOC.  The defintintion 
for KLOC is confusing.
<td type=Valid>
<td type=UserCreated>
<td type=UserFound>
<td type=Injected>
<td type=Removed>
<td type=Checklist>
<tr>
<td type=CreateDate>1998/06/18
<td type=DocID>intro.pdf
<td type=FixTime>
<td type=Location>Sect 1.4
<td type=Occurrences>1
<td type=DefectType>10:Syntax
<td type=Severity>
<td type=Description>Why is this called motivation? Seems very jarring to me.
<td type=Valid>
<td type=UserCreated>
<td type=UserFound>
<td type=Injected>
<td type=Removed>
<td type=Checklist>
<tr>
<td type=CreateDate>1998/06/18
<td type=DocID>intro.pdf
<td type=FixTime>
<td type=Location>p4 2nd para
<td type=Occurrences>1
<td type=DefectType>10:Syntax
<td type=Severity>
<td type=Description>Very long complex sentence. "Although the general good..."
<td type=Valid>
<td type=UserCreated>
<td type=UserFound>
<td type=Injected>
<td type=Removed>
<td type=Checklist>
<tr>
<td type=CreateDate>1998/06/18
<td type=DocID>intro.pdf
<td type=FixTime>
<td type=Location>p5 2nd para
<td type=Occurrences>1
<td type=DefectType>20:Organization
<td type=Severity>
<td type=Description>I think this paragraph should be introduced somewhere else.
<td type=Valid>
<td type=UserCreated>
<td type=UserFound>
<td type=Injected>
<td type=Removed>
<td type=Checklist>
<tr>
<td type=CreateDate>1998/06/18
<td type=DocID>intro.pdf
<td type=FixTime>
<td type=Location>p6 1st para
<td type=Occurrences>1
<td type=DefectType>20:Organization
<td type=Severity>
<td type=Description>"These two problems..." sounds like a conclusion and not a 
hypothesis. 
<td type=Valid>
<td type=UserCreated>
<td type=UserFound>
<td type=Injected>
<td type=Removed>
<td type=Checklist>
<tr>
<td type=CreateDate>1998/06/18
<td type=DocID>intro.pdf
<td type=FixTime>
<td type=Location>p6 3rd para
<td type=Occurrences>1
<td type=DefectType>10:Syntax
<td type=Severity>
<td type=Description>"(2) the addition of" is awkward.  Maybe "added four" instead.
<td type=Valid>
<td type=UserCreated>
<td type=UserFound>
<td type=Injected>
<td type=Removed>
<td type=Checklist>
<tr>
<td type=CreateDate>1998/06/18
<td type=DocID>intro.pdf
<td type=FixTime>
<td type=Location>p6,7
<td type=Occurrences>1
<td type=DefectType>10:Syntax
<td type=Severity>
<td type=Description>The term mistakes is used then errors.  Are mistakes erorrs or
is there some distinction between mistakes and errors?
<td type=Valid>
<td type=UserCreated>
<td type=UserFound>
<td type=Injected>
<td type=Removed>
<td type=Checklist>
<tr>
<td type=CreateDate>1998/06/18
<td type=DocID>
<td type=FixTime>
<td type=Location>
<td type=Occurrences>
<td type=DefectType>
<td type=Severity>
<td type=Description>
<td type=Valid>
<td type=UserCreated>
<td type=UserFound>
<td type=Injected>
<td type=Removed>
<td type=Checklist>
</table>

</body>
</html>
