(defun r ()
  (interactive)
  (let ((pnt (point)))
    (while (re-search-forward "^([0-9]+)" nil t)
      (delete-region (match-beginning 0) (match-end 0))
      )
    (goto-char pnt)
    (while (search-forward "\\#" nil t)
      (delete-region (match-beginning 0) (match-end 0))
      )
    (goto-char pnt)
    (while (search-forward "\\\\" nil t)
      (delete-region (match-beginning 0) (match-end 0))
      (insert " & \\\\"))
    (goto-char pnt)
    ))

(defun r2 ()
  (interactive)
  (let ((pnt (point)))
    (while (search-forward "\\\\" nil t)
      (delete-region (match-beginning 0) (match-end 0))
      (insert " & \\\\"))
    (goto-char pnt)
    ))

