#! /usr/local/bin/tcsh -f

latex textemplate
dvips textemplate.dvi -o textemplate.ps 
distill -resolution 2400 -colordownsample off -graydownsample off -monodownsample off -cmykimagestorgb off textemplate.ps
