<html>
<head>
<title>LEAP Data File</title>
</head>
<body>
<table border>
<tr>
<td>DRL Plain 1.0.0
<tr>
<th>CreateDate<th>DocID<th>FixTime<th>Location<th>Occurrences<th>DefectType<th>Severity<th>Description<th>Valid<th>UserCreated<th>UserFound<th>Injected<th>Removed<th>Checklist
<tr>
<td type=CreateDate>1998/06/19
<td type=DocID>intro.pdf
<td type=FixTime>
<td type=Location>01-01
<td type=Occurrences>1
<td type=DefectType>20:Organization
<td type=Severity>
<td type=Description>Suggestion: "Why is software quality important" for Section 1.1 title.
This motivates the accompanying text better.
<td type=Valid>
<td type=UserCreated>
<td type=UserFound>
<td type=Injected>
<td type=Removed>
<td type=Checklist>
<tr>
<td type=CreateDate>1998/06/19
<td type=DocID>intro.pdf
<td type=FixTime>
<td type=Location>02-03
<td type=Occurrences>1
<td type=DefectType>10:Syntax
<td type=Severity>
<td type=Description>"programmers have been" -> "the beginning of"
<td type=Valid>
<td type=UserCreated>
<td type=UserFound>
<td type=Injected>
<td type=Removed>
<td type=Checklist>
<tr>
<td type=CreateDate>1998/06/19
<td type=DocID>intro.pdf
<td type=FixTime>
<td type=Location>02-06
<td type=Occurrences>1
<td type=DefectType>10:Syntax
<td type=Severity>
<td type=Description>"At first" -> Into the 1960's
<td type=Valid>
<td type=UserCreated>
<td type=UserFound>
<td type=Injected>
<td type=Removed>
<td type=Checklist>
<tr>
<td type=CreateDate>1998/06/19
<td type=DocID>intro.pdf
<td type=FixTime>
<td type=Location>02-09
<td type=Occurrences>
<td type=DefectType>30: Content
<td type=Severity>
<td type=Description>Might add: "In fact, this gave rise to the software engineering
adage that "You can't test in quality".
<td type=Valid>
<td type=UserCreated>
<td type=UserFound>
<td type=Injected>
<td type=Removed>
<td type=Checklist>
<tr>
<td type=CreateDate>1998/06/19
<td type=DocID>intro.pdf
<td type=FixTime>
<td type=Location>03-00
<td type=Occurrences>7
<td type=DefectType>11: Passive voice
<td type=Severity>
<td type=Description>Lots of passive voice on this page. I have suggested corrections
on the hardcopy. In general, try to avoid passive voice.  I will note
other occurrences with a "p.v" on the hardcopy.
<td type=Valid>
<td type=UserCreated>
<td type=UserFound>
<td type=Injected>
<td type=Removed>
<td type=Checklist>
<tr>
<td type=CreateDate>1998/06/19
<td type=DocID>intro.pdf
<td type=FixTime>
<td type=Location>04-00
<td type=Occurrences>1
<td type=DefectType>20:Organization
<td type=Severity>
<td type=Description>Suggestion: entitle Section 1.4 "Motivation for this research"
to clarify what you are trying to motivate.
<td type=Valid>
<td type=UserCreated>
<td type=UserFound>
<td type=Injected>
<td type=Removed>
<td type=Checklist>
<tr>
<td type=CreateDate>1998/06/19
<td type=DocID>intro.pdf
<td type=FixTime>
<td type=Location>04-00
<td type=Occurrences>1
<td type=DefectType>20:Organization
<td type=Severity>
<td type=Description>The caption for Figure 1.1 looks just like text. If the thesis
guidelines allow it, you may want to use \ls{1} and \em 
within captions in order to single space and italicize caption
text. This would make it clearly distinct from chapter text.
<td type=Valid>
<td type=UserCreated>
<td type=UserFound>
<td type=Injected>
<td type=Removed>
<td type=Checklist>
<tr>
<td type=CreateDate>1998/06/19
<td type=DocID>intro.pdf
<td type=FixTime>
<td type=Location>05-20
<td type=Occurrences>1
<td type=DefectType>30: Content
<td type=Severity>
<td type=Description>I would add here:  'Note that although an "automated" PSP can
essentially automate all of the analysis stage calculations, there are 
limits to its ability to automate the collection stage work. The collection
stage is still quite "manual" in nature.
<td type=Valid>
<td type=UserCreated>
<td type=UserFound>
<td type=Injected>
<td type=Removed>
<td type=Checklist>
<tr>
<td type=CreateDate>1998/06/19
<td type=DocID>intro.pdf
<td type=FixTime>
<td type=Location>06-01
<td type=Occurrences>1
<td type=DefectType>20:Organization
<td type=Severity>
<td type=Description>Rename 1.5 title: "Hypothesis of this research"
<td type=Valid>
<td type=UserCreated>
<td type=UserFound>
<td type=Injected>
<td type=Removed>
<td type=Checklist>
<tr>
<td type=CreateDate>1998/06/19
<td type=DocID>intro.pdf
<td type=FixTime>
<td type=Location>01-01
<td type=Occurrences>1
<td type=DefectType>10:Syntax
<td type=Severity>
<td type=Description>Avoid "we". Use "I".
<td type=Valid>
<td type=UserCreated>
<td type=UserFound>
<td type=Injected>
<td type=Removed>
<td type=Checklist>
<tr>
<td type=CreateDate>1998/06/19
<td type=DocID>intro.pdf
<td type=FixTime>
<td type=Location>06-11
<td type=Occurrences>1
<td type=DefectType>30: Content
<td type=Severity>
<td type=Description>"using data collected from the next PSPclass taught by Dr. Johnson."
<td type=Valid>
<td type=UserCreated>
<td type=UserFound>
<td type=Injected>
<td type=Removed>
<td type=Checklist>
<tr>
<td type=CreateDate>1998/06/19
<td type=DocID>intro.pdf
<td type=FixTime>
<td type=Location>07-16
<td type=Occurrences>1
<td type=DefectType>30: Content
<td type=Severity>
<td type=Description>You might want to insert this at the start of Section 1.7:
"When this research project started, Dr. Johnson and I 
expected to find between 50 and 100 errors in the class data. 
This estimate was way off: we found 1539 errors.
<td type=Valid>
<td type=UserCreated>
<td type=UserFound>
<td type=Injected>
<td type=Removed>
<td type=Checklist>
<tr>
<td type=CreateDate>1998/06/19
<td type=DocID>intro.pdf
<td type=FixTime>
<td type=Location>08-11
<td type=Occurrences>1
<td type=DefectType>30: Content
<td type=Severity>
<td type=Description>Motivate this paragraph, perhaps as follows:
One might also hypothesize that these error simply constitute "noise"
and do not substantially impact upon the overall analysis results.
To test  this hypothesis, we recalculated some of the major
metrics using the (partially) corrected data.  We found....
<td type=Valid>
<td type=UserCreated>
<td type=UserFound>
<td type=Injected>
<td type=Removed>
<td type=Checklist>
<tr>
<td type=CreateDate>1998/06/19
<td type=DocID>
<td type=FixTime>
<td type=Location>
<td type=Occurrences>
<td type=DefectType>
<td type=Severity>
<td type=Description>
<td type=Valid>
<td type=UserCreated>
<td type=UserFound>
<td type=Injected>
<td type=Removed>
<td type=Checklist>
</table>

</body>
</html>
