latex input: mmd-article-header
Title: Lights Off. Game On. The Kukui Cup
Author: Robert S. Brewer, George E. Lee, Philip M. Johnson
Date: December 10, 2011
Base Header Level: 2
latex mode: memoir
latex input: mmd-article-begin-doc
latex footer: mmd-memoir-footer

<center><h1>Lights Out. Game On. The Kukui Cup.</h1></center>

# Motivation #

One of the great challenges facing Hawaii today is our dependence on foreign oil, which negatively affects our security, our economy, our environment, and our next generation's ability to have a healthy, prosperous, sustainable lifestyle.

To address this problem, the [Hawaii Clean Energy Initiative][HCEI] (HCEI) was formed between the State of Hawaii, HECO, and the US Department of Energy. HCEI is a roadmap to achieve 70% clean energy by 2030 with 40% coming from locally generated renewable sources, and 30% from efficiency measures.

Energy efficiency can come in the form of more efficient appliances, but it can also come from changes in how we choose to use energy. The energy consumption of identical homes can differ by a factor of 2 or more based on the behavior of the occupants.

Our research seeks to answer the following question: how can we support individuals and groups in making positive changes in their behavior with respect to energy usage through both real world activities, and virtual activities mediated through information technology. The Kukui Cup is our first attempt at answering this question.

# What is the Kukui Cup? #

The Kukui Cup is an advanced energy challenge that combines real-time energy feedback, energy education, multiple forms of incentives, and gamification techniques to support positive changes in energy behavior. The inaugural Kukui Cup was held in Fall, 2011, for over 1,000 first year students living in the 4 Hale Aloha residence halls at the University of Hawaii at Manoa. We are planning the second Kukui Cup for Fall, 2012.

# How it works #

The Kukui Cup consists of two separate competitions. In the energy conservation competition, floors try to use the least electricity during each round. The energy use is monitored through smart meters installed on each floor. Due to the electrical infrastructure of the residence halls, we are only able to monitor electricity meaningfully on pairs of floors. These pairs of floors are called "lounges" because they share a central lounge, and are labeled from A to E.

Participants earn points individually by performing activities on the website like watching videos we have created and answering a question about the video correctly. The activities have been designed to increase the *energy literacy* of the participants, and help them to conserve energy.

The other competition is the point competition. Students participating in the Kukui Cup challenge can log in to the [Kukui Cup website][kukuicup-website] during the challenge to gain access to their current power consumption and cumulative energy use. The site also provides short videos developed specifically for the competition that provide insight into Hawaii energy issues, and students can earn points by correctly answering questions about each video's content.

Other ways to earn points include meeting a daily energy conservation goal, attending short, interactive "workshops" about energy,  or going on excursions to power plants, wind farms, and more. Participation can lead to prizes including t-shirts, pizza parties, and gift certificates. By playing the game, students become knowledgeable about the energy challenges facing Hawaii and how to change their own behavior and those around them to use energy more efficiently.

We now go into more depth on aspects of the Kukui Cup experience.

## Smart Grid Game ##

One of the core components of Kukui Cup is the Smart Grid. This is the primary place users go to to earn points in the competition. Tasks are organized into a grid of squares and organized by category columns. There are 4 different types of tasks a user can complete in the Smart Grid: activities, commitments, events, and excursions.

Activities are the most basic task available in the Smart Grid. In order to get points for an activity, a user will have to submit a response for administrator approval. Administrators can log in and access an admin page to approve or deny submissions. If a submission is approved, the user will receive the points for that submission. Otherwise, a user will be sent a website notification informing them that their submission was not approved. The user can change and resubmit their response and still earn the full point value for that task.

Commitments are pledges that the user will do something sustainable for a period of 5 days. Examples include reducing shower time, taking the stairs, and turning off the lights when you leave the room. Because these commitments are not verifiable, they are typically worth fewer points than activities. Furthermore, a user can only have up to 5 active commitments at any given time. After the 5 day period is up, the user can confirm that they completed the commitment to receive their points. They can then sign up for another commitment, including the one they just completed.

Events and excursions are tied to real world activities. Events are held on campus while excursions take place off campus. Seating is limited, so users are asked to register in advance. Users that do so are provided with a two point signup bonus. Users can also set up a reminder that is sent to their email and/or their mobile phone. Once the event or excursion takes place, they will receive an attendance code that can be redeemed on the website. To discourage users from signing up and not attending, a 2 point penalty is assessed to users who do not submit an attendance code (presumably because they failed to attend the event).

## Energy Conservation Game ##

The energy conservation game is supported through the Kukui Cup website in several ways. The energy page displays the real-time power being used by each lounge so that participants can see how their actions impact energy use. The energy page also provides a scoreboard that shows the energy use of each lounge so that players can track how their lounge is doing compared to other lounges.

Players are also provided with a daily energy goal. The goal for each floor is typically a percent reduction from their baseline usage before the competition. Users can go to the energy page and see if they are on track for their daily energy goal. If the floor did reach their goal, each member of the floor receives 20 points. The energy goal game provides a link between the energy conservation competition, and the point competition.

## Incentives ##

For each round of the competition, prizes were awarded to the lounge using the least energy, the lounge with the most points, the individual with the most points in every lounge, and the individual with the most points overall. The Kukui Cup website shows the prizes available, and who is the current leader in each category.

One problem we faced is motivating those players who were not going to have the highest score. To provide them with an incentive, we developed a Raffle Game. For every 25 points a player has, they earn one virtual raffle ticket. Each round of the competition has a set of raffle prizes, and each player can allocate their tickets dynamically among the prizes. The odds of winning each prize depend on how many players allocate tickets to the prize.

# Implementing The Kukui Cup #

The open source web application that implements the virtual aspects of the Kukui Cup is called Makahiki. The source code available via [Github][Github] at [http://github.com/keokilee/makahiki][makahiki-github].

We explored various frameworks and existing projects. Our goal was to find something that got us started quickly, but allowed us to extend the basic functionality to suit our needs. We decided on Pinax, a suite of reusable applications for the Django web framework.

![Diagram of Makahiki architecture](makahiki-architecture-crop.png)

## Authentication ##

One of the primary design goals of Makahiki was to allow users to log in and view personalized information. Furthermore, since Makahiki was primarily designed to support college and university energy competitions, it needs to support authentication via a central authentication service (CAS). We used an open source project called 'django_cas' to support CAS authentication. Makahiki also supports regular username and password authentication, which is provided by the Django web framework. This is useful if a CAS server is unavailable or if the website is being shown to users outside of the college or university.

## Quest Engine ##

The main challenge we faced when designing Makahiki was providing adequate help to the user. We want the website to be intuitive, but a new user coming to an energy competition website does not know what to expect. The quest engine, inspired by games such as World of Warcraft, is our solution to this issue. Quests are to guide the user through the various workflows of the site, like answering a question, signing up for an event, or allocating a raffle ticket. Competition administrators can determine how quests are unlocked and completed using a limited subset of Python.

## Energy Data ##

Another major component of the system is the energy page. Makahiki itself does not store energy information. We use [WattDepot][wattdepot-website], an open source storage engine for energy data we developed, to store the meter data from the individual floors. However, since energy calculations occur over time, they can be expensive if we have to recalculate energy values every time the page is accessed. Instead, we used Google Spreadsheets as a 'Cloud Cache'. Using the GData API, WattDepot updates the cache periodically with power and energy information for the individual floors. Using the GData Javascript API, the user's browser accesses the cache in order to get energy information.

# Publications #

 * Robert S. Brewer, [The Kukui Cup: Shaping Everyday Energy Use Via a Dorm Energy Competition][CHI-everyday-practice], Proceedings of the CHI 2011 Workshop on Everyday Practice and Sustainable HCI, May 2011.
 * Robert S. Brewer, George E. Lee, Yongwen Xu, Caterina Desiato, Michelle Katchuck, Philip M. Johnson, [Lights Off. Game On. The Kukui Cup: A Dorm Energy Competition][CHI-gamification], Proceedings of the CHI 2011 Workshop on Gamification, May 2011.
 * Robert S. Brewer, George E. Lee, Philip M. Johnson, [The Kukui Cup: a Dorm Energy Competition Focused on Sustainable Behavior Change and Energy Literacy][HICSS-2011], Proceedings of the 44th Hawaii International Conference on System Sciences, January 2011.
 * Robert S. Brewer and Philip M. Johnson, [WattDepot: An open source software ecosystem for enterprise-scale energy data collection, storage, analysis, and visualization][wattdepot-paper], in Proceedings of 1st IEEE International Conference on Smart Grid Communications, October 2010.

# Our sponsors #

The Kukui Cup is grateful for financial support from:

 * the [National Science Foundation][NSF-website] under [grant 1017126][NSF-grant]
 * the [Center for Renewable Energy and Island Sustainability][REIS-website]
 * [University of Hawaii at Manoa Student Housing Services][housing-website]
 * [University of Hawaii at Manoa Facilities Management][facilities-website]
 * the [State of Hawaii Department of Business, Economic Development, and Tourism][DBEDT-website]
 * the [University of Hawaii Department of Information and Computer Sciences][ICS-website]

# Our team #

The Kukui Cup project team is led by Professor Philip Johnson from the Department of Information and Computer Sciences (ICS) at the University of Hawaii. Team members from ICS include: Robert Brewer, Yongwen Xu, George Lee, Greg Burgess, and Nathan Dorman. Team members from the Department of Communications include: Michelle Katchuck, Hana Bowers, and Risa Khamsi. Alex Young joins us from the Departments of Art and Spanish, Kaveh Abhari from Shidler College of Business, and Chris Zorn comes from the University of Hawaii Lab School.

[HCEI]: http://www.hawaiicleanenergyinitiative.org/
[CHI-everyday-practice]: http://csdl.ics.hawaii.edu/techreports/11-03/11-03.pdf
[CHI-gamification]: http://csdl.ics.hawaii.edu/techreports/11-02/11-02.pdf
[HICSS-2011]: http://csdl.ics.hawaii.edu/techreports/10-07/10-07.pdf
[NSF-website]: http://www.nsf.gov/
[NSF-grant]: http://www.nsf.gov/awardsearch/showAward.do?AwardNumber=1017126
[REIS-website]: http://reis.manoa.hawaii.edu/
[housing-website]: http://manoa.hawaii.edu/housing/
[facilities-website]: http://manoa.hawaii.edu/facilities/
[DBEDT-website]: http://energy.hawaii.gov/
[ICS-website]: http://www.ics.hawaii.edu/
[Github]: https://github.com/
[makahiki-github]: http://github.com/keokilee/makahiki
[kukuicup-website]: http://kukuicup.manoa.hawaii.edu
[wattdepot-website]: http://code.google.com/p/wattdepot/
[wattdepot-paper]: http://csdl.ics.hawaii.edu/techreports/10-05/10-05.pdf
