#! /usr/local/bin/tcsh -f

latex 06-13
bibtex 06-13
latex 06-13
latex 06-13
dvips 06-13.dvi -o 06-13.ps 
distill -resolution 2400 -colordownsample off -graydownsample off -monodownsample off -cmykimagestorgb off 06-13.ps

