#!/bin/sh -x

rsync                                                    \
     --delete                                            \
     --rsync-path=/usr/bin/rsync                         \
     -a                                                  \
     -e ssh                                              \
     -v                                                  \
     -P                                                  \
     -x							 \
     . dasha.ics.hawaii.edu:/Users/csdl/Sites/public_html/techreports/08-02

echo exit value is $?
