#!/bin/sh

## Simple script to upload the PDF version of the tech report to the
## appropriate directory on dasha. Note that it assumes that the PDF is
## named after the tech report number, and the tech report directory will
## have to be created and sudo chowned beforehand.
 
TR_NUM=`basename $PWD`
scp -p ${TR_NUM}.pdf dasha.ics.hawaii.edu:/Users/csdl/Sites/public_html/techreports/${TR_NUM}
