#! /usr/local/bin/tcsh -f

latex 06-12
bibtex 06-12
latex 06-12
latex 06-12
dvips 06-12.dvi -o 06-12.ps 
#distill -resolution 2400 -colordownsample off -graydownsample off -monodownsample off -cmykimagestorgb off 06-04.ps

