#! /usr/local/bin/tcsh -f

latex 06-12
dvips 06-12.dvi -o 06-12.ps 
#distill -compatlevel 2.1 -alwaysembed -resolution 2400 -colordownsample off -graydownsample off -monodownsample off -cmykimagestorgb off 06-04.ps

#ps2pdf 06-12.ps




