<html>
<head>
<title>LEAP Data File</title>
</head>
<body>
<table border>
<tr>
<td>DRL Plain 1.0.0
<tr>
<th>CreateDate<th>DocID<th>FixTime<th>Location<th>Occurrences<th>DefectType<th>Severity<th>Description<th>Valid<th>UserCreated<th>UserFound<th>Injected<th>Removed<th>Checklist
<tr>
<td type=CreateDate>1998/07/16
<td type=DocID>ch5.pdf
<td type=FixTime>
<td type=Location>34-1
<td type=Occurrences>1
<td type=DefectType>20:Organization
<td type=Severity>
<td type=Description>Fixed:  Section 5.1.2 should have an introductory paragraph
explaining what an "Operational Scenario" actually is
before you jump into them in 5.1.2.1.
<td type=Valid>
<td type=UserCreated>
<td type=UserFound>
<td type=Injected>
<td type=Removed>
<td type=Checklist>
<tr>
<td type=CreateDate>1998/07/16
<td type=DocID>ch5.pdf
<td type=FixTime>
<td type=Location>43
<td type=Occurrences>1
<td type=DefectType>30: Content
<td type=Severity>
<td type=Description>This would probably be a good place to add a paragraph
about your use of this tool over the past year (two?)
<td type=Valid>
<td type=UserCreated>
<td type=UserFound>
<td type=Injected>
<td type=Removed>
<td type=Checklist>
<tr>
<td type=CreateDate>1998/07/16
<td type=DocID>ch5.pdf
<td type=FixTime>
<td type=Location>45
<td type=Occurrences>1
<td type=DefectType>20:Organization
<td type=Severity>
<td type=Description>Fixed:  I believe the caption for Figures should go under the figure,
not above it.
<td type=Valid>
<td type=UserCreated>
<td type=UserFound>
<td type=Injected>
<td type=Removed>
<td type=Checklist>
<tr>
<td type=CreateDate>1998/07/16
<td type=DocID>ch5.pdf
<td type=FixTime>
<td type=Location>45
<td type=Occurrences>1
<td type=DefectType>30: Content
<td type=Severity>
<td type=Description>Fixed:  Can you provide some sort of small usage scenario for
the error tracking tool at the end of this section? Or perhaps
just some additional explanation of what the sample report
means in Figure 5.6?
<td type=Valid>
<td type=UserCreated>
<td type=UserFound>
<td type=Injected>
<td type=Removed>
<td type=Checklist>
<tr>
<td type=CreateDate>1998/07/16
<td type=DocID>
<td type=FixTime>
<td type=Location>
<td type=Occurrences>
<td type=DefectType>
<td type=Severity>
<td type=Description>
<td type=Valid>
<td type=UserCreated>
<td type=UserFound>
<td type=Injected>
<td type=Removed>
<td type=Checklist>
</table>

</body>
</html>
