#! /usr/local/bin/tcsh -f

latex 05-01
bibtex 05-01
latex 05-01
latex 05-01
dvips 05-01.dvi -o 05-01.ps 
distill -resolution 2400 -colordownsample off -graydownsample off -monodownsample off -cmykimagestorgb off 05-01.ps
